Repository envoyproxy/gateway, pull requests merged in 2022-10, with the labels that each got.

#469 increase require eventually timeout
  internal/xds/translator/runner/runner_test.go
Labels: area/ci

#372 document workaround for conformance tests on Mac
  DEVELOPER.md
Labels: documentation

#482 delete unneeded gatewayclass delete logic
  internal/gatewayapi/runner/runner_test.go
  internal/message/types.go
  internal/message/types_test.go
  internal/provider/kubernetes/gatewayclass.go
Labels: bug, provider/kubernetes

#486 Updates Dev Guide
  DEVELOPER.md
Labels: documentation

#487 Fixes Supported Kube Version
  DEVELOPER.md
  docs/user/QUICKSTART.md
Labels: bug, documentation

#488 add `make kube-demo` to DEVELOPER docs
  DEVELOPER.md
Labels: documentation

#491 Adds Roadmap Doc
  README.md
  docs/design/ROADMAP.md
Labels: documentation

#509 Updates Versions in Compatibility Matrix
  docs/intro/compatibility.rst
Labels: documentation

#480 provider: only store resource if spec has changed
  internal/provider/kubernetes/gateway.go
  internal/provider/kubernetes/httproute.go
  internal/provider/kubernetes/kubernetes_test.go
Labels: provider/kubernetes

#537 remove xds ir listener sort
  internal/gatewayapi/sort.go
Labels: area/translator

#510 Merges Release Manifests
  .github/workflows/release.yaml
  kustomization.yaml
Labels: area/ci

#534 chore: run conformance tests with identical ports
  .github/workflows/build_and_test.yaml
  test/conformance/conformance_test.go
  tools/make/kube.mk
Labels: area/ci

#495 Updates ParentRef Status Conditions
  internal/gatewayapi/testdata/httproute-with-header-filter-duplicate-add-multiple-filters.out.yaml
  internal/gatewayapi/testdata/httproute-with-header-filter-duplicate-adds.out.yaml
  internal/gatewayapi/testdata/httproute-with-header-filter-duplicate-remove-multiple-filters.out.yaml
  internal/gatewayapi/testdata/httproute-with-header-filter-duplicate-removes.out.yaml
  internal/gatewayapi/testdata/httproute-with-header-filter-empty-headers.out.yaml
  internal/gatewayapi/testdata/httproute-with-header-filter-invalid-headers.out.yaml
  internal/gatewayapi/testdata/httproute-with-header-filter-no-valid-headers.out.yaml
  internal/gatewayapi/testdata/httproute-with-redirect-filter-invalid-filter-type.out.yaml
  internal/gatewayapi/testdata/httproute-with-redirect-filter-invalid-scheme.out.yaml
  internal/gatewayapi/testdata/httproute-with-redirect-filter-invalid-status.out.yaml
  internal/gatewayapi/translator.go
Labels: area/translator

#552 Removes run-kube-local Target
  tools/make/kube.mk
Labels: area/ci

#521 chore: add local shellcheck tools
  tools/make/golang.mk
  tools/make/lint.mk
  tools/make/tools.mk
Labels: area/ci

#560 Fixes URL in Quickstart Doc
  docs/user/QUICKSTART.md
Labels: documentation

#530 feat: set mgr to interface
  internal/infrastructure/kubernetes/infra.go
  internal/infrastructure/kubernetes/infra_test.go
  internal/infrastructure/manager.go
  internal/infrastructure/runner/runner.go
Labels: area/infra-mgr

#557 Fix intermittent failures
  .gitignore
  docs/design/watching.md
  internal/infrastructure/runner/runner.go
  internal/message/watchutil.go
  internal/message/watchutil_test.go
  internal/provider/kubernetes/gateway.go
  internal/provider/kubernetes/httproute.go
  internal/provider/kubernetes/tlsroute.go
  internal/provider/runner/runner_test.go
  internal/xds/server/runner/runner.go
  internal/xds/translator/runner/runner.go
  internal/xds/translator/runner/runner_test.go
Labels: area/translator

#580 use RefNotPermitted reason for invalid cross-namespace TLS cert ref
  internal/gatewayapi/testdata/gateway-with-listener-with-invalid-tls-configuration-secret-in-other-namespace.out.yaml
  internal/gatewayapi/translator.go
  test/conformance/conformance_test.go
Labels: bug, area/translator, area/conformance

#546 Moves Changelogs to Release Notes
  .github/workflows/release.yaml
  release-notes/v0.1.0.yaml
  release-notes/v0.2.0-rc1.yaml
  release-notes/v0.2.0-rc2.yaml
  tools/make/kube.mk
Labels: documentation

#561 Updates Dev Doc to Use Gateway Ns/Name
  DEVELOPER.md
Labels: documentation

#584 Updates Spellcheck Ignore
  tools/linter/codespell/.codespell.skip
Labels: documentation, area/ci

#582 Updates Release Branch Naming
  docs/dev/releasing.md
Labels: documentation

#489 Reorganizes Dev Guide and Adds Conformance for Mac
  DEVELOPER.md
  README.md
  docs/dev/README.md
  docs/user/QUICKSTART.md
Labels: documentation

#569 feat: support canary release of EG
  .github/workflows/build_and_test.yaml
  .github/workflows/pre_release.yaml
Labels: enhancement, area/ci

#549 Fix Service object remove from resource map from route controller
  internal/provider/kubernetes/httproute.go
  internal/provider/kubernetes/kubernetes.go
  internal/provider/kubernetes/store.go
  internal/provider/kubernetes/store_test.go
  internal/provider/kubernetes/tlsroute.go
Labels: bug, provider/kubernetes

#565 Adds HTTPRoute Redirect Docs
  docs/user/http-redirect.md
Labels: documentation

#607 Add a Printable method to Xds IR
  internal/gatewayapi/runner/runner.go
  internal/ir/xds.go
  internal/ir/xds_test.go
Labels: area/translator

#604 dont add filterChainMatch for wildcard hostnames
  internal/gatewayapi/testdata/tlsroute-with-partial-wildcard-hostname.in.yaml
  internal/gatewayapi/testdata/tlsroute-with-partial-wildcard-hostname.out.yaml
  internal/gatewayapi/translator.go
  internal/xds/translator/listener.go
  internal/xds/translator/testdata/out/xds-ir/simple-tls.listeners.yaml
Labels: area/translator

#602 Updates Dev Guide for Hashed Naming
  docs/dev/README.md
Labels: documentation

#618 Adds Xunzhuo as a Maintainer
  CODEOWNERS.md
Labels: documentation, decision

#630 Updates Quickstart Guide Links for v0.2.0 Release
  docs/user/quickstart.md
Labels: documentation

#635 Adds v0.2 Release Announcement Doc
  docs/index.rst
  docs/releases/v0.2.md
Labels: documentation

#636 Reorganizes Sphinx Docs
  README.md
  docs/about_docs.rst
  docs/design_docs.rst
  docs/dev/CODE_OF_CONDUCT.md
  docs/dev/CONTRIBUTING.md
  docs/dev/DOCS.md
  docs/dev_docs.rst
  docs/index.rst
  docs/releases.rst
  docs/roadmap.rst
  docs/user_docs.rst
Labels: documentation

#634 Updates Release Doc
  docs/dev/releasing.md
Labels: documentation

#542 Adds Secure Gateway User Doc
  .gitignore
  docs/user/secure-gateways.md
  docs/user_docs.rst
Labels: documentation

#652 bring in fixes from go-control-plane
  go.mod
  go.sum
Labels: area/xds-server

#645 Updates Design Docs for v0.2
  docs/design/config-api.md
  docs/design/gatewayapi-translator.md
  docs/design/system-design.md
  docs/design/watching.md
Labels: documentation
