Repository envoyproxy/gateway, pull requests merged in 2022-11, with the labels that each got.

#665 Adds Release Details Doc
  docs/releases.rst
  docs/releases/README.md
Labels: documentation

#609 feat: support user-facing version
  docs/latest/conf.py
  internal/cmd/root.go
  internal/cmd/version/version.go
  internal/cmd/versions.go
  tools/make/golang.mk
  tools/make/tools.mk
  tools/src/goversion/go.mod
  tools/src/goversion/go.sum
  tools/src/goversion/pin.go
Labels: documentation

#694 Updates User Docs to Use Echoserver
  docs/latest/user/http-redirect.md
  docs/latest/user/secure-gateways.md
  docs/v0.2.0/user/http-redirect.md
  docs/v0.2.0/user/secure-gateways.md
Labels: bug, documentation

#640 Cleans-Up Docs
  docs/latest/about_docs.rst
  docs/latest/get_involved.rst
  docs/latest/index.rst
  docs/latest/intro/index.rst
  docs/latest/user_docs.rst
  docs/v0.2.0/about_docs.rst
  docs/v0.2.0/get_involved.rst
  docs/v0.2.0/index.rst
  docs/v0.2.0/intro/index.rst
  docs/v0.2.0/user_docs.rst
Labels: documentation

#666 Enhance HTTP IR to support GRPCRoute
  internal/ir/xds.go
Labels: area/ir

#715 Updates Readme Slack and Google Group
  README.md
Labels: documentation

#722 Fixes Envoy Deployment Ref in Dev Doc
  docs/latest/dev/README.md
  docs/v0.2.0/dev/README.md
Labels: bug, documentation

#710 opt: run conformance test concurrently in multi-kube-version
  .github/workflows/build_and_test.yaml
  tools/make/image.mk
  tools/make/kube.mk
Labels: area/ci, area/conformance

#741 add -e to echo command
  tools/make/common.mk
  tools/make/docs.mk
  tools/make/golang.mk
  tools/make/kube.mk
  tools/make/lint.mk
Labels: bug
