Repository envoyproxy/gateway, pull requests merged in 2022-12, with the labels that each got.

#702 [provider] refactoring kubernetes provider to single reconciler
  internal/cmd/server.go
  internal/gatewayapi/helpers_v1alpha2.go
  internal/gatewayapi/runner/runner.go
  internal/gatewayapi/runner/runner_test.go
  internal/gatewayapi/translator.go
  internal/gatewayapi/zz_generated.deepcopy.go
  internal/message/types.go
  internal/message/types_test.go
  internal/provider/kubernetes/controller.go
  internal/provider/kubernetes/gateway.go
  internal/provider/kubernetes/gateway_test.go
  internal/provider/kubernetes/gatewayclass.go
  internal/provider/kubernetes/gatewayclass_test.go
  internal/provider/kubernetes/helpers.go
  internal/provider/kubernetes/httproute.go
  internal/provider/kubernetes/httproute_test.go
  internal/provider/kubernetes/kubernetes.go
  internal/provider/kubernetes/kubernetes_test.go
  internal/provider/kubernetes/predicates.go
  internal/provider/kubernetes/routes.go
  internal/provider/kubernetes/store.go
  internal/provider/kubernetes/store_test.go
  internal/provider/kubernetes/tlsroute.go
  internal/status/status.go
  test/conformance/conformance_test.go
  tools/make/kube.mk
Labels: provider/kubernetes, priority/high

#771 Adds Step to Quickstart
  docs/latest/user/quickstart.md
  docs/v0.2.0/user/quickstart.md
Labels: documentation

#744 ci: add go mod linter to lint target
  api/config/v1alpha1/groupversion_info.go
  docs/latest/dev/README.md
  internal/status/status.go
  tools/github-actions/setup-deps/action.yaml
  tools/make/golang.mk
  tools/src/controller-gen/go.mod
  tools/src/golangci-lint/go.mod
  tools/src/kind/go.mod
  tools/src/kustomize/go.mod
  tools/src/kustomize/pin.go
  tools/src/setup-envtest/go.mod
Labels: area/ci

#779 Adds Namespace Support to Server Config Type
  internal/cmd/certgen.go
  internal/cmd/server.go
  internal/crypto/certgen.go
  internal/crypto/certgen_test.go
  internal/envoygateway/config/config.go
  internal/envoygateway/config/config_test.go
  internal/gatewayapi/runner/runner_test.go
  internal/infrastructure/kubernetes/configmap_test.go
  internal/infrastructure/kubernetes/deployment_test.go
  internal/infrastructure/kubernetes/infra.go
  internal/infrastructure/kubernetes/service_test.go
  internal/infrastructure/kubernetes/serviceaccount_test.go
  internal/infrastructure/manager.go
  internal/provider/kubernetes/controller.go
  internal/provider/kubernetes/kubernetes_test.go
  internal/provider/kubernetes/predicates.go
  internal/xds/translator/runner/runner_test.go
Labels: area/config

#793 Add ReferenceGrant Support for Routes
  internal/provider/kubernetes/controller.go
  internal/provider/kubernetes/helpers.go
  internal/provider/kubernetes/routes.go
  test/conformance/conformance_test.go
Labels: provider/kubernetes, release-note

#745 fix: start xds server watchable map panics
  internal/xds/server/runner/runner.go
Labels: bug, area/translator, area/infra-mgr

#735 governmence: add Tencent to steering committee
  GOVERNANCE.md
Labels: decision
