Repository envoyproxy/gateway, pull requests merged in 2023-04, with the labels that each got.

#1107 Update GatewayClass status based on EnvoyProxy validation
  api/config/v1alpha1/testdata/different-dynamic-resources-user-bootstrap.yaml
  api/config/v1alpha1/testdata/different-xds-cluster-address-bootstrap.yaml
  api/config/v1alpha1/testdata/missing-admin-address-user-bootstrap.yaml
  api/config/v1alpha1/testdata/valid-user-bootstrap.yaml
  api/config/v1alpha1/validate.go
  api/config/v1alpha1/validate_test.go
  internal/provider/kubernetes/controller.go
  internal/xds/bootstrap/bootstrap.go
  internal/xds/server/runner/runner.go
  internal/xds/server/runner/runner_test.go
Labels: priority/high

#1218 feat: support envoy ratelimit pod & container resources & securitycontext settings.
  api/config/v1alpha1/envoygateway_types.go
  api/config/v1alpha1/helpers.go
  api/config/v1alpha1/validate_test.go
  api/config/v1alpha1/zz_generated.deepcopy.go
  docs/latest/api/config_types.md
  internal/envoygateway/config/decoder_test.go
  internal/envoygateway/config/testdata/decoder/in/gateway-ratelimit.yaml
  internal/globalratelimit/runner/runner.go
  internal/infrastructure/kubernetes/deployment_test.go
  internal/infrastructure/kubernetes/infra.go
  internal/infrastructure/kubernetes/proxy_deployment_test.go
  internal/infrastructure/kubernetes/proxy_service_test.go
  internal/infrastructure/kubernetes/ratelimit_configmap.go
  internal/infrastructure/kubernetes/ratelimit_configmap_test.go
  internal/infrastructure/kubernetes/ratelimit_deployment.go
  internal/infrastructure/kubernetes/ratelimit_deployment_test.go
  internal/infrastructure/kubernetes/ratelimit_service_test.go
  internal/infrastructure/kubernetes/ratelimit_serviceaccount_test.go
  internal/infrastructure/kubernetes/service_test.go
  internal/infrastructure/runner/runner.go
  internal/ir/ratelimit_infra.go
  internal/ir/zz_generated.deepcopy.go
  internal/xds/translator/ratelimit.go
Labels: enhancement, area/api, area/config, provider/kubernetes

#1274 ci: auto assign reviewer-team when open pr
  .github/workflows/assignee.yaml
Labels: area/ci

#1286 doc: update envoyproxy dynamic configuration doc.
  docs/latest/design/system-design.md
Labels: documentation

#1285 Extensions: pass watched resources to IR
  internal/gatewayapi/filters.go
  internal/gatewayapi/route.go
  internal/gatewayapi/runner/runner.go
  internal/gatewayapi/testdata/extensions/httproute-with-extension-filter-invalid-group.in.yaml
  internal/gatewayapi/testdata/extensions/httproute-with-extension-filter-invalid-group.out.yaml
  internal/gatewayapi/testdata/extensions/httproute-with-non-matching-extension-filter.in.yaml
  internal/gatewayapi/testdata/extensions/httproute-with-non-matching-extension-filter.out.yaml
  internal/gatewayapi/testdata/extensions/httproute-with-unsupported-extension-filter.in.yaml
  internal/gatewayapi/testdata/extensions/httproute-with-unsupported-extension-filter.out.yaml
  internal/gatewayapi/testdata/extensions/httproute-with-valid-extension-filter.in.yaml
  internal/gatewayapi/testdata/extensions/httproute-with-valid-extension-filter.out.yaml
  internal/gatewayapi/translator.go
  internal/gatewayapi/translator_test.go
  internal/ir/xds.go
Labels: release-blocker

#1297 fix expose ratelimit image.
  api/config/v1alpha1/helpers.go
  api/config/v1alpha1/shared_types.go
  api/config/v1alpha1/validate_test.go
  docs/latest/user/rate-limit.md
  internal/cmd/version/version.go
  internal/envoygateway/config/decoder_test.go
  internal/envoygateway/config/testdata/decoder/in/gateway-ratelimit.yaml
  internal/infrastructure/kubernetes/ratelimit_deployment.go
  internal/infrastructure/kubernetes/ratelimit_deployment_test.go
Labels: bug

#1314 docs: add pull request template & update contributing docs.
  .github/PULL_REQUEST_TEMPLATE.md
  docs/latest/dev/CONTRIBUTING.md
  docs/latest/dev/README.md
Labels: documentation

#1333 docs: for xds bootstrap
  docs/latest/user/customize-envoyproxy.md
  docs/latest/user/egctl.md
Labels: documentation

#1334 docs: move rsa+edsca cert docs into secure gateways doc
  docs/latest/user/rsa+ecdsa-secure-gateways.md
  docs/latest/user/secure-gateways.md
Labels: documentation

#1332 fix: add the namespace resource within helm templates
  charts/gateway-helm/templates/certgen-rbac.yaml
  charts/gateway-helm/templates/certgen.yaml
  charts/gateway-helm/templates/envoy-gateway-config.yaml
  charts/gateway-helm/templates/envoy-gateway-deployment.yaml
  charts/gateway-helm/templates/envoy-gateway-metrics-service.yaml
  charts/gateway-helm/templates/envoy-gateway-service.yaml
  charts/gateway-helm/templates/infra-manager-rbac.yaml
  charts/gateway-helm/templates/leader-election-rbac.yaml
  charts/gateway-helm/templates/metrics-reader-rbac.yaml
  charts/gateway-helm/templates/namespace.yaml
  charts/gateway-helm/values.tmpl.yaml
  tools/make/kube.mk
Labels: area/installation

#1335 doc: add a user doc on deployment mode
  docs/latest/user/deployment-mode.md
  docs/latest/user_docs.rst
Labels: documentation

#1312 ci: setup action for cherrypick
  .github/workflows/cherrypick.yaml
  docs/latest/dev/releasing.md
Labels: area/ci

#1337 refactor: followup kubernetes/infrastruture refactoring.
  internal/infrastructure/kubernetes/applier/apply.go
  internal/infrastructure/kubernetes/infra.go
  internal/infrastructure/kubernetes/infra_client.go
  internal/infrastructure/kubernetes/infra_resource.go
  internal/infrastructure/kubernetes/proxy/resource.go
  internal/infrastructure/kubernetes/proxy/resource_provider.go
  internal/infrastructure/kubernetes/proxy/resource_provider_test.go
  internal/infrastructure/kubernetes/proxy/resource_test.go
  internal/infrastructure/kubernetes/proxy_configmap_test.go
  internal/infrastructure/kubernetes/proxy_deployment_test.go
  internal/infrastructure/kubernetes/proxy_infra.go
  internal/infrastructure/kubernetes/proxy_service_test.go
  internal/infrastructure/kubernetes/proxy_serviceaccount_test.go
  internal/infrastructure/kubernetes/ratelimit/deployment.go
  internal/infrastructure/kubernetes/ratelimit/resource.go
  internal/infrastructure/kubernetes/ratelimit/resource_provider.go
  internal/infrastructure/kubernetes/ratelimit/resource_provider_test.go
  internal/infrastructure/kubernetes/ratelimit_configmap_test.go
  internal/infrastructure/kubernetes/ratelimit_deployment_test.go
  internal/infrastructure/kubernetes/ratelimit_infra.go
  internal/infrastructure/kubernetes/ratelimit_service_test.go
  internal/infrastructure/kubernetes/ratelimit_serviceaccount_test.go
  internal/infrastructure/kubernetes/resource/resource.go
  internal/infrastructure/kubernetes/resource/resource_test.go
Labels: enhancement, area/infra-mgr, provider, refactor

#1366 chore: bump sphinx to v6.2.1 and myst-parser to v1.0.0
  .github/dependabot.yml
  tools/src/sphinx-build/requirements.txt
Labels: cherrypick/release-v0.4

#1363 feat: support envoyproxy & ratelimit deployment container env configu…
  api/config/v1alpha1/shared_types.go
  api/config/v1alpha1/zz_generated.deepcopy.go
  charts/gateway-helm/crds/generated/config.gateway.envoyproxy.io_envoyproxies.yaml
  docs/latest/api/config_types.md
  internal/envoygateway/config/decoder_test.go
  internal/envoygateway/config/testdata/decoder/in/gateway-ratelimit.yaml
  internal/gatewayapi/testdata/envoyproxy-valid.in.yaml
  internal/gatewayapi/testdata/envoyproxy-valid.out.yaml
  internal/infrastructure/kubernetes/proxy/resource.go
  internal/infrastructure/kubernetes/proxy/resource_provider.go
  internal/infrastructure/kubernetes/proxy/resource_provider_test.go
  internal/infrastructure/kubernetes/proxy/testdata/deployments/default-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/extension-env.yaml
  internal/infrastructure/kubernetes/ratelimit/deployment.go
  internal/infrastructure/kubernetes/ratelimit/resource.go
  internal/infrastructure/kubernetes/ratelimit/resource_provider.go
  internal/infrastructure/kubernetes/ratelimit/resource_provider_test.go
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default-env.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/extension-env.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/override-env.yaml
  internal/infrastructure/kubernetes/ratelimit_deployment_test.go
  tools/src/crd-ref-docs/pin.go
Labels: enhancement, area/api, area/config

#1375 kubernetes: support custom cluster dns domain
  charts/gateway-helm/README.md
  charts/gateway-helm/templates/certgen.yaml
  charts/gateway-helm/templates/envoy-gateway-deployment.yaml
  charts/gateway-helm/values.tmpl.yaml
  internal/cmd/egctl/translate.go
  internal/crypto/certgen.go
  internal/envoygateway/config/config.go
  internal/infrastructure/kubernetes/ratelimit/resource.go
  internal/infrastructure/kubernetes/ratelimit/resource_provider_test.go
  internal/xds/translator/runner/runner.go
  internal/xds/translator/testdata/in/xds-ir/ratelimit-custom-domain.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-custom-domain.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-custom-domain.endpoints.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-custom-domain.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-custom-domain.routes.yaml
  internal/xds/translator/translator_test.go
Labels: provider/kubernetes
