Repository envoyproxy/gateway, pull requests merged in 2023-10, with the labels that each got.

#1935 opt: codes
  internal/cmd/server.go
  internal/gatewayapi/runner/runner.go
  internal/globalratelimit/runner/runner.go
  internal/infrastructure/runner/runner.go
  internal/message/types.go
  internal/provider/kubernetes/controller.go
  internal/provider/kubernetes/kubernetes.go
  internal/provider/kubernetes/kubernetes_test.go
  internal/provider/runner/runner.go
  internal/xds/server/runner/runner.go
  internal/xds/translator/runner/runner.go
Labels: refactor

#1952 Design: add favicons to eg website
  site/static/favicons/android-chrome-192x192.png
  site/static/favicons/android-chrome-512x512.png
  site/static/favicons/apple-touch-icon.png
  site/static/favicons/favicon-16x16.png
  site/static/favicons/favicon-32x32.png
  site/static/favicons/favicon.ico
  site/static/favicons/site.webmanifest
Labels: area/website

#1959 fix: Remove ErrHTTPRouteMatchEmpty check for Xds IR
  internal/ir/xds.go
  internal/ir/xds_test.go
Labels: bug

#1967 feat: separate debug server with admin
  api/v1alpha1/envoygateway_helpers.go
  api/v1alpha1/envoygateway_types.go
  api/v1alpha1/envoyproxy_types.go
  api/v1alpha1/validation/validate_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  internal/cmd/server.go
  internal/debug/server.go
  internal/debug/server_test.go
  internal/infrastructure/kubernetes/proxy/resource_provider_test.go
  internal/provider/kubernetes/kubernetes.go
  site/content/en/latest/api/extension_types.md
  site/content/en/latest/design/pprof.md
Labels: release-note

#2015 Enable proxy prometheus by default
  api/v1alpha1/envoyproxy_types.go
  api/v1alpha1/metric_types.go
  api/v1alpha1/validation/envoyproxy_validate.go
  api/v1alpha1/validation/envoyproxy_validate_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
  examples/kubernetes/metric/disable-prometheus.yaml
  internal/cmd/egctl/testdata/translate/out/authn-single-route-single-match-to-xds.all.json
  internal/cmd/egctl/testdata/translate/out/authn-single-route-single-match-to-xds.all.yaml
  internal/cmd/egctl/testdata/translate/out/authn-single-route-single-match-to-xds.bootstrap.yaml
  internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml
  internal/cmd/egctl/testdata/translate/out/envoy-patch-policy.all.yaml
  internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.json
  internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.yaml
  internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.bootstrap.yaml
  internal/cmd/egctl/testdata/translate/out/invalid-envoyproxy.all.yaml
  internal/cmd/egctl/testdata/translate/out/rate-limit-filter-single-route-single-match-to-xds.all.json
  internal/cmd/egctl/testdata/translate/out/rate-limit-filter-single-route-single-match-to-xds.all.yaml
  internal/cmd/egctl/testdata/translate/out/rate-limit-filter-single-route-single-match-to-xds.bootstrap.yaml
  internal/cmd/egctl/testdata/translate/out/valid-envoyproxy.all.yaml
  internal/gatewayapi/listener.go
  internal/gatewayapi/listener_test.go
  internal/gatewayapi/testdata/envoyproxy-valid.out.yaml
  internal/gatewayapi/testdata/merge-invalid-multiple-gateways.out.yaml
  internal/gatewayapi/testdata/merge-valid-multiple-gateways-multiple-routes.out.yaml
  internal/gatewayapi/testdata/merge-valid-multiple-gateways.out.yaml
  internal/infrastructure/kubernetes/proxy/resource.go
  internal/infrastructure/kubernetes/proxy/resource_provider.go
  internal/infrastructure/kubernetes/proxy/resource_provider_test.go
  internal/xds/bootstrap/bootstrap.go
  internal/xds/bootstrap/bootstrap_test.go
  internal/xds/bootstrap/testdata/disable-prometheus.yaml
  site/content/en/latest/api/extension_types.md
  site/content/en/latest/design/metrics.md
  site/content/en/latest/user/proxy-observability.md
Labels: release-note

#1905 fix: egctl stats invalid format
  internal/cmd/egctl/envoy_stats.go
  internal/cmd/egctl/stats.go
Labels: area/egctl

#1981 design(docs/api): control plane metrics monitoring
  api/v1alpha1/envoygateway_helpers.go
  api/v1alpha1/envoygateway_metrics_types.go
  api/v1alpha1/envoygateway_types.go
  api/v1alpha1/envoyproxy_metric_types.go
  api/v1alpha1/validation/envoygateway_validate.go
  api/v1alpha1/validation/envoygateway_validate_test.go
  api/v1alpha1/validation/envoyproxy_validate.go
  api/v1alpha1/validation/envoyproxy_validate_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  internal/infrastructure/kubernetes/proxy/resource_provider_test.go
  internal/xds/bootstrap/bootstrap_test.go
  site/content/en/latest/api/extension_types.md
  site/content/en/latest/design/eg-metrics.md
  site/content/en/latest/install/install-helm.md
Labels: area/observability

#1950 design: SecurityPolicy
  site/content/en/latest/design/security-policy.md
Labels: design

#2064 team: add new reviewers of eg
  OWNERS
Labels: community

#1982 feat: add control plane metrics library
  api/v1alpha1/envoygateway_helpers.go
  api/v1alpha1/shared_types.go
  api/v1alpha1/validation/envoygateway_validate_test.go
  api/v1alpha1/validation/envoyproxy_validate_test.go
  go.mod
  go.sum
  internal/admin/server.go
  internal/cmd/server.go
  internal/metrics/metadata.go
  internal/metrics/options.go
  internal/metrics/otel_label.go
  internal/metrics/otel_metric_counter.go
  internal/metrics/otel_metric_gauge.go
  internal/metrics/otel_metric_histogram.go
  internal/metrics/otel_metric_sink.go
  internal/metrics/register.go
  internal/metrics/sample_counter_test.go
  internal/metrics/sample_gauge_test.go
  internal/metrics/sample_histogram_test.go
  internal/metrics/units.go
  site/content/en/latest/design/eg-metrics.md
Labels: priority/high, area/observability

#2083 remove RateLimitFilter in favor of BackendTrafficPolicy
  api/v1alpha1/backendtrafficpolicy_types.go
  api/v1alpha1/ratelimit_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/gateway-helm/crds/generated/gateway.envoyproxy.io_ratelimitfilters.yaml
  internal/cmd/egctl/testdata/translate/in/rate-limit-filter-single-route-single-match-to-xds.yaml
  internal/cmd/egctl/testdata/translate/out/rate-limit-filter-single-route-single-match-to-xds.all.json
  internal/cmd/egctl/testdata/translate/out/rate-limit-filter-single-route-single-match-to-xds.all.yaml
  internal/cmd/egctl/testdata/translate/out/rate-limit-filter-single-route-single-match-to-xds.bootstrap.yaml
  internal/cmd/egctl/testdata/translate/out/rate-limit-filter-single-route-single-match-to-xds.cluster.yaml
  internal/cmd/egctl/testdata/translate/out/rate-limit-filter-single-route-single-match-to-xds.endpoint.yaml
  internal/cmd/egctl/testdata/translate/out/rate-limit-filter-single-route-single-match-to-xds.listener.yaml
  internal/cmd/egctl/testdata/translate/out/rate-limit-filter-single-route-single-match-to-xds.route.yaml
  internal/cmd/egctl/translate.go
  internal/cmd/egctl/translate_test.go
  internal/gatewayapi/filters.go
  internal/gatewayapi/helpers.go
  internal/gatewayapi/helpers_test.go
  internal/gatewayapi/resource.go
  internal/gatewayapi/route.go
  internal/gatewayapi/testdata/grpcroute-with-valid-ratelimitfilter.in.yaml
  internal/gatewayapi/testdata/grpcroute-with-valid-ratelimitfilter.out.yaml
  internal/gatewayapi/testdata/httproute-with-distinct-sourcecidr-ratelimit.in.yaml
  internal/gatewayapi/testdata/httproute-with-distinct-sourcecidr-ratelimit.out.yaml
  internal/gatewayapi/testdata/httproute-with-invalid-ratelimitfilter.in.yaml
  internal/gatewayapi/testdata/httproute-with-invalid-ratelimitfilter.out.yaml
  internal/gatewayapi/testdata/httproute-with-sourcecidr-ratelimit.in.yaml
  internal/gatewayapi/testdata/httproute-with-sourcecidr-ratelimit.out.yaml
  internal/gatewayapi/testdata/httproute-with-valid-ratelimitfilter.in.yaml
  internal/gatewayapi/testdata/httproute-with-valid-ratelimitfilter.out.yaml
  internal/gatewayapi/zz_generated.deepcopy.go
  internal/provider/kubernetes/controller.go
  internal/provider/kubernetes/filters.go
  internal/provider/kubernetes/kubernetes_test.go
  internal/provider/kubernetes/predicates.go
  internal/provider/kubernetes/routes.go
  internal/provider/kubernetes/routes_test.go
  internal/provider/kubernetes/test/utils.go
  site/content/en/latest/api/extension_types.md
  site/content/en/latest/user/rate-limit.md
  test/e2e/testdata/ratelimit-based-jwt-claims.yaml
  test/e2e/testdata/ratelimit-block-all-ips.yaml
  tools/crd-ref-docs/config.yaml
Labels: release-note
