Repository envoyproxy/gateway, pull requests merged in 2023-08, with the labels that each got.

#1735 test: add setvalue unit tests coverage
  internal/utils/field/field.go
  internal/utils/field/field_test.go
Labels: area/testing

#1737 Add request mirroring doc
  docs/latest/user/http-request-mirroring.md
  docs/latest/user_docs.rst
Labels: documentation

#1733 docs: Add user docs for EnvoyPatchPolicy
  docs/latest/user/envoy-patch-policy.md
  docs/latest/user_docs.rst
Labels: documentation

#1757 rm deprecated SourceIP field
  api/v1alpha1/ratelimitfilter_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/gateway-helm/crds/generated/gateway.envoyproxy.io_ratelimitfilters.yaml
  docs/latest/api/extension_types.md
  internal/gatewayapi/filters.go
  internal/gatewayapi/testdata/httproute-with-distinct-sourcecidr-ratelimit.in.yaml
  internal/gatewayapi/testdata/httproute-with-distinct-sourcecidr-ratelimit.out.yaml
  internal/gatewayapi/testdata/httproute-with-sourcecidr-ratelimit.in.yaml
  internal/gatewayapi/testdata/httproute-with-sourcecidr-ratelimit.out.yaml
Labels: release-note

#1545 refactor: split api helpers to envoygateway,envoyproxy and kubernetes helpers.
  api/config/v1alpha1/envoygateway_helpers.go
  api/config/v1alpha1/envoyproxy_helpers.go
  api/config/v1alpha1/helpers.go
  api/config/v1alpha1/kubernetes_helpers.go
  api/config/v1alpha1/validation/validate_test.go
  internal/infrastructure/kubernetes/proxy/resource.go
  internal/infrastructure/kubernetes/proxy/resource_test.go
Labels: area/api, refactor

#1778 api: bump gwapi to v0.8.0-rc1
  charts/gateway-helm/crds/gatewayapi-crds.yaml
  go.mod
  go.sum
  internal/status/conditions_test.go
  internal/status/gateway.go
  internal/status/gateway_test.go
Labels: area/api

#1766 follow-up(doc, fix): support for grpcroute ratelimitfilter
  docs/latest/user/rate-limit.md
  internal/provider/kubernetes/controller.go
  internal/provider/kubernetes/filters.go
  internal/provider/kubernetes/routes.go
Labels: bug, documentation, refactor

#1791 feat: support merging user and default bootstrap configurations
  api/config/v1alpha1/envoyproxy_types.go
  api/config/v1alpha1/validation/testdata/merge-user-bootstrap.yaml
  api/config/v1alpha1/validation/validate.go
  api/config/v1alpha1/validation/validate_test.go
  api/config/v1alpha1/zz_generated.deepcopy.go
  charts/gateway-helm/crds/generated/config.gateway.envoyproxy.io_envoyproxies.yaml
  docs/latest/api/config_types.md
  docs/latest/user/customize-envoyproxy.md
  internal/cmd/egctl/testdata/translate/in/invalid-envoyproxy.yaml
  internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml
  internal/cmd/egctl/testdata/translate/out/invalid-envoyproxy.all.yaml
  internal/cmd/egctl/translate.go
  internal/infrastructure/kubernetes/proxy/resource.go
  internal/infrastructure/kubernetes/proxy/resource_provider_test.go
  internal/utils/yaml/yaml.go
  internal/utils/yaml/yaml_test.go
  internal/xds/bootstrap/util.go
Labels: release-note
