Repository envoyproxy/gateway, pull requests merged in 2023-02, with the labels that each got.

#951 Fixes RateLimit and Authn Index Funcs
  internal/gatewayapi/helpers.go
  internal/provider/kubernetes/controller.go
  internal/provider/kubernetes/kubernetes_test.go
  internal/provider/kubernetes/test/utils.go
Labels: provider/kubernetes

#934 Adds JWT Authn Support to XDS Translator
  api/v1alpha1/authenticationfilter_types.go
  api/v1alpha1/validation/authenticationfilter.go
  api/v1alpha1/validation/authenticationfilter_test.go
  internal/gatewayapi/testdata/httproute-with-valid-multi-match-multi-authenfilter.in.yaml
  internal/gatewayapi/testdata/httproute-with-valid-multi-match-multi-authenfilter.out.yaml
  internal/ir/xds.go
  internal/provider/kubernetes/config/crd/bases/gateway.envoyproxy.io_authenticationfilters.yaml
  internal/xds/translator/authentication.go
  internal/xds/translator/listener.go
  internal/xds/translator/ratelimit.go
  internal/xds/translator/route.go
  internal/xds/translator/testdata/in/xds-ir/authn-multi-route-multi-provider.yaml
  internal/xds/translator/testdata/in/xds-ir/authn-multi-route-single-provider.yaml
  internal/xds/translator/testdata/in/xds-ir/authn-ratelimit.yaml
  internal/xds/translator/testdata/in/xds-ir/authn-single-route-single-match.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-multi-route-multi-provider.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-multi-route-multi-provider.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-multi-route-multi-provider.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-multi-route-single-provider.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-multi-route-single-provider.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-multi-route-single-provider.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-ratelimit.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-ratelimit.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-ratelimit.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-single-route-single-match.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-single-route-single-match.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-single-route-single-match.routes.yaml
  internal/xds/translator/translator.go
  internal/xds/translator/translator_test.go
Labels: area/translator

#959 Updates Release Doc to Set Proxy Image
  docs/latest/dev/releasing.md
Labels: documentation

#958 Sets Envoy Proxy Image to v1.25
  internal/ir/infra.go
Labels: area/config, area/ir

#962 Grammar fixes for GRPCRoute related comments
  internal/gatewayapi/contexts.go
  internal/gatewayapi/filters.go
  internal/gatewayapi/route.go
Labels: documentation

#966 Updates Dev Release Guide
  docs/latest/dev/releasing.md
Labels: documentation

#974 xds: Deprecated http2_protocol_options
  internal/xds/translator/authentication.go
  internal/xds/translator/ratelimit.go
  internal/xds/translator/testdata/out/xds-ir/authn-multi-route-multi-provider.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-multi-route-single-provider.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-ratelimit.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-single-route-single-match.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit.clusters.yaml
Labels: area/translator

#991 Adds JWT Authn User Docs
  docs/latest/dev/README.md
  docs/latest/user/authn.md
  docs/latest/user_docs.rst
  examples/kubernetes/authn/jwks.json
  examples/kubernetes/authn/jwt.yaml
  examples/kubernetes/authn/test.jwt
Labels: documentation

#989 user docs for global rate limit
  docs/latest/user/rate-limit.md
Labels: documentation

#1010 Updates API godocs for improved markdown rendering
  api/config/v1alpha1/doc.go
  api/config/v1alpha1/envoygateway_types.go
  api/config/v1alpha1/envoyproxy_types.go
  api/config/v1alpha1/shared_types.go
  api/v1alpha1/authenticationfilter_types.go
  api/v1alpha1/doc.go
  api/v1alpha1/ratelimitfilter_types.go
  docs/latest/api/config_types.md
  docs/latest/api/extension_types.md
  internal/provider/kubernetes/config/crd/bases/config.gateway.envoyproxy.io_envoyproxies.yaml
  internal/provider/kubernetes/config/crd/bases/gateway.envoyproxy.io_authenticationfilters.yaml
  internal/provider/kubernetes/config/crd/bases/gateway.envoyproxy.io_ratelimitfilters.yaml
Labels: documentation, area/api

#896 conformance: enable GatewayClassObservedGenerationBump
  test/conformance/conformance_test.go
Labels: area/ci

#1014 Run all conformance tests except redirect tests
  test/conformance/conformance_test.go
Labels: area/ci, release-note

#1019 remove empty route error check in auth xds logic
  internal/xds/translator/authentication.go
Labels: bug, priority/high

#1021 Removes GatewayObservedGenerationBump and HTTPRouteObservedGenerationBump Tests
  test/conformance/conformance_test.go
Labels: bug, release-note, priority/high

#1017 Add Gateway API support doc
  docs/latest/design/gatewayapi-support.md
  docs/v0.2.0/design_docs.rst
Labels: documentation

#1018 Adds Cherry-Pick Steps to Release Doc
  docs/latest/dev/releasing.md
Labels: documentation

#1020 update to validate 1.26
  .github/workflows/build_and_test.yaml
  tools/hack/create-cluster.sh
Labels: area/ci

#1002 Bumps Compatibility Matrix for v0.3
  docs/latest/intro/compatibility.rst
Labels: documentation

#1013 release(v0.3.0): add release notes and release announcement
  docs/latest/releases.rst
  docs/latest/releases/v0.3.md
  release-notes/v0.3.0.yaml
Labels: documentation, release-note

#1026 Updates Gateway API Support Doc
  docs/latest/design/egctl.md
  docs/latest/design/gatewayapi-support.md
  docs/latest/design/request-authentication.md
  docs/latest/design_docs.rst
Labels: documentation

#997 refactor infrastructure and add ratelimit tests.
  internal/infrastructure/kubernetes/configmap.go
  internal/infrastructure/kubernetes/deployment.go
  internal/infrastructure/kubernetes/infra.go
  internal/infrastructure/kubernetes/labels.go
  internal/infrastructure/kubernetes/proxy_configmap.go
  internal/infrastructure/kubernetes/proxy_configmap_test.go
  internal/infrastructure/kubernetes/proxy_deployment.go
  internal/infrastructure/kubernetes/proxy_deployment_test.go
  internal/infrastructure/kubernetes/proxy_infra.go
  internal/infrastructure/kubernetes/proxy_infra_test.go
  internal/infrastructure/kubernetes/proxy_labels.go
  internal/infrastructure/kubernetes/proxy_labels_test.go
  internal/infrastructure/kubernetes/proxy_service.go
  internal/infrastructure/kubernetes/proxy_service_test.go
  internal/infrastructure/kubernetes/proxy_serviceaccount.go
  internal/infrastructure/kubernetes/proxy_serviceaccount_test.go
  internal/infrastructure/kubernetes/ratelimit_configmap.go
  internal/infrastructure/kubernetes/ratelimit_configmap_test.go
  internal/infrastructure/kubernetes/ratelimit_deployment.go
  internal/infrastructure/kubernetes/ratelimit_deployment_test.go
  internal/infrastructure/kubernetes/ratelimit_infra.go
  internal/infrastructure/kubernetes/ratelimit_labels.go
  internal/infrastructure/kubernetes/ratelimit_labels_test.go
  internal/infrastructure/kubernetes/ratelimit_service.go
  internal/infrastructure/kubernetes/ratelimit_service_test.go
  internal/infrastructure/kubernetes/ratelimit_serviceaccount.go
  internal/infrastructure/kubernetes/ratelimit_serviceaccount_test.go
  internal/infrastructure/kubernetes/service.go
  internal/infrastructure/kubernetes/serviceaccount.go
  internal/message/watchutil.go
Labels: area/ci

#1030 Moves PR 1026 Docs to v0.3
  docs/v0.3.0/design/gatewayapi-support.md
  docs/v0.3.0/design_docs.rst
Labels: documentation

#1033 use API docs links in authn & rateLimit doc
  docs/latest/user/authn.md
  docs/latest/user/rate-limit.md
  docs/v0.3.0/user/authn.md
  docs/v0.3.0/user/rate-limit.md
Labels: documentation

#946 ratelimit(api): support SourceIP
  api/v1alpha1/ratelimitfilter_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  docs/latest/design/ratelimit.md
  internal/provider/kubernetes/config/crd/bases/gateway.envoyproxy.io_ratelimitfilters.yaml
Labels: documentation, area/api

#1015 translator: refactor authn and ratelimit to use buildXdsCluster
  internal/ir/xds.go
  internal/xds/translator/authentication.go
  internal/xds/translator/cluster.go
  internal/xds/translator/ratelimit.go
  internal/xds/translator/testdata/out/xds-ir/authn-multi-route-multi-provider.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-multi-route-single-provider.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-ratelimit.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-single-route-single-match.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit.clusters.yaml
  internal/xds/translator/translator.go
Labels: area/translator

#987 Update 0.4.0 roadmap items
  docs/latest/design/roadmap.md
  docs/v0.3.0/design/roadmap.md
Labels: documentation

#1083 feat: add bootstrap/listener/cluster/route configdump support
  internal/cmd/egctl/config.go
  internal/cmd/egctl/config_test.go
  internal/cmd/egctl/testdata/config/in/in.all.json
  internal/cmd/egctl/testdata/config/out.json
  internal/cmd/egctl/testdata/config/out/out.all.json
  internal/cmd/egctl/testdata/config/out/out.all.yaml
  internal/cmd/egctl/testdata/config/out/out.bootstrap.json
  internal/cmd/egctl/testdata/config/out/out.bootstrap.yaml
  internal/cmd/egctl/testdata/config/out/out.cluster.json
  internal/cmd/egctl/testdata/config/out/out.cluster.yaml
  internal/cmd/egctl/testdata/config/out/out.listener.json
  internal/cmd/egctl/testdata/config/out/out.listener.yaml
  internal/cmd/egctl/testdata/config/out/out.route.json
  internal/cmd/egctl/testdata/config/out/out.route.yaml
  internal/cmd/egctl/testdata/translate/in/from-gateway-api-to-xds.yaml
  internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.json
  internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.yaml
  internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.bootstrap.yaml
  internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.cluster.yaml
  internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.listener.yaml
  internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.route.yaml
  internal/cmd/egctl/translate.go
  internal/cmd/egctl/translate_test.go
  internal/cmd/egctl/utils.go
Labels: area/config, area/egctl

#1084 chore: add examples of egctl x translate examples
  internal/cmd/egctl/experimental.go
  internal/cmd/egctl/translate.go
Labels: area/egctl
