Repository envoyproxy/gateway, pull requests merged in 2023-05, with the labels that each got.

#1376 docs: user docs for envoyproxy & ratelimit container env settings.
  docs/latest/user/customize-envoyproxy.md
  docs/latest/user/rate-limit.md
Labels: documentation, area/api, area/config

#1388 chore: GHA to request reviews from gateway-reviewers
  .github/workflows/cc_reviewers_pr.yaml
Labels: area/ci

#1382 design: Run Envoy Gateway locally on host
  docs/latest/design/local-envoy-gateway.md
  docs/latest/design_docs.rst
Labels: area/api, area/infra-mgr, provider

#1401 docs: missing NodePort service type description comment
  api/config/v1alpha1/shared_types.go
  charts/gateway-helm/crds/generated/config.gateway.envoyproxy.io_envoyproxies.yaml
  docs/latest/api/config_types.md
Labels: area/api, area/config

#1404 ci: allow cherrypick create pull-requests
  .github/workflows/cherrypick.yaml
Labels: area/ci

#1294 feat: support envoy ratelimit TLS settings.
  api/config/v1alpha1/envoygateway_types.go
  api/config/v1alpha1/zz_generated.deepcopy.go
  docs/latest/api/config_types.md
  docs/latest/user/rate-limit.md
  internal/envoygateway/config/decoder_test.go
  internal/envoygateway/config/testdata/decoder/in/gateway-ratelimit.yaml
  internal/extension/registry/extension_manager.go
  internal/infrastructure/kubernetes/proxy_infra_test.go
  internal/infrastructure/kubernetes/ratelimit/resource.go
  internal/infrastructure/kubernetes/ratelimit/resource_provider.go
  internal/infrastructure/kubernetes/ratelimit/resource_provider_test.go
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/redis-tls-settings.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/tolerations.yaml
  internal/infrastructure/kubernetes/ratelimit_infra.go
  internal/infrastructure/kubernetes/ratelimit_infra_test.go
  internal/kubernetes/secret.go
Labels: enhancement, area/api

#1414 feat: optimize edsClusterConfig for the association between cluster resources and endpoint resources in envoy's configdump?include_eds interface
  internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml
  internal/cmd/egctl/testdata/translate/out/echo-gateway-api.cluster.yaml
  internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.json
  internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.all.yaml
  internal/cmd/egctl/testdata/translate/out/from-gateway-api-to-xds.cluster.yaml
  internal/xds/translator/cluster.go
  internal/xds/translator/testdata/out/extension-xds-ir/http-route-extension-filter.clusters.yaml
  internal/xds/translator/testdata/out/extension-xds-ir/http-route.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-multi-route-multi-provider.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-multi-route-single-provider.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-ratelimit.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/authn-single-route-single-match.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-direct-response.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-mirror.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-redirect.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-regex.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-request-headers.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-response-add-headers.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-response-add-remove-headers.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-response-remove-headers.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-root-path-url-prefix.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-fullpath.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-host.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-prefix.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-weighted-backend.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-weighted-invalid-backend.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-stripped-host-port.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http2-route.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/multiple-listeners-same-port.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/multiple-simple-tcp-route-same-port.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-custom-domain.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-sourceip.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/simple-tls.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/tcp-route-complex.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/tcp-route-simple.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/tcp-route-weighted-backend.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/tls-route-passthrough.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/udp-route.clusters.yaml
Labels: enhancement, area/translator, area/egctl

#1413 feat: add API for Deployment Mode
  api/config/v1alpha1/envoygateway_types.go
  api/config/v1alpha1/zz_generated.deepcopy.go
  docs/latest/api/config_types.md
Labels: cherrypick/release-v0.4

#1430 chore: use patch for finalizer updates on GC
  charts/gateway-helm/templates/generated/rbac/roles.yaml
  internal/provider/kubernetes/controller.go
  internal/provider/kubernetes/rbac.go
Labels: cherrypick/release-v0.4

#1425 feat: add spew dump for envoy-gateway config when starting up
  go.mod
  internal/cmd/server.go
Labels: enhancement, area/config, cherrypick/release-v0.4

#1424 feat: support deployment volumes and container volumeMounts.
  api/config/v1alpha1/shared_types.go
  api/config/v1alpha1/zz_generated.deepcopy.go
  charts/gateway-helm/crds/generated/config.gateway.envoyproxy.io_envoyproxies.yaml
  docs/latest/api/config_types.md
  docs/latest/user/customize-envoyproxy.md
  internal/gatewayapi/testdata/envoyproxy-valid.in.yaml
  internal/gatewayapi/testdata/envoyproxy-valid.out.yaml
  internal/infrastructure/kubernetes/proxy/resource.go
  internal/infrastructure/kubernetes/proxy/resource_provider.go
  internal/infrastructure/kubernetes/proxy/resource_provider_test.go
  internal/infrastructure/kubernetes/proxy/testdata/deployments/volumes.yaml
  internal/infrastructure/kubernetes/ratelimit/resource.go
  internal/infrastructure/kubernetes/ratelimit/resource_provider.go
  internal/infrastructure/kubernetes/ratelimit/resource_provider_test.go
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/volumes.yaml
  internal/infrastructure/kubernetes/resource/resource.go
  internal/infrastructure/kubernetes/resource/resource_test.go
Labels: enhancement, area/api, area/config

#1407 Observability: Access Logging
  api/config/v1alpha1/accesslogging_types.go
  api/config/v1alpha1/envoyproxy_types.go
  api/config/v1alpha1/zz_generated.deepcopy.go
  charts/eg/crds/generated/config.gateway.envoyproxy.io_envoyproxies.yaml
  charts/gateway-helm/crds/generated/config.gateway.envoyproxy.io_envoyproxies.yaml
  docs/latest/api/config_types.md
  docs/latest/design/accesslogging.md
  tools/linter/codespell/.codespell.ignorewords
Labels: area/api, area/observability

#1450 fix: Run yamllint on generated Install Manifests
  .github/workflows/build_and_test.yaml
  charts/gateway-helm/templates/certgen.yaml
  tools/linter/yamllint/.yamllint
Labels: area/ci

#1082 feat: add namespaced all proxies config dump support
  internal/cmd/egctl/config.go
  internal/cmd/egctl/config_cmd.go
  internal/infrastructure/kubernetes/proxy/resource.go
  internal/kubernetes/client.go
Labels: area/egctl, area/tooling

#1451 follow-up: removal of the ratelimit ir
  internal/cmd/server.go
  internal/globalratelimit/runner/runner.go
  internal/infrastructure/kubernetes/ratelimit/resource_provider.go
  internal/infrastructure/kubernetes/ratelimit/resource_provider_test.go
  internal/infrastructure/kubernetes/ratelimit_deployment_test.go
  internal/infrastructure/kubernetes/ratelimit_infra.go
  internal/infrastructure/kubernetes/ratelimit_infra_test.go
  internal/infrastructure/kubernetes/ratelimit_service_test.go
  internal/infrastructure/kubernetes/ratelimit_serviceaccount_test.go
  internal/infrastructure/manager.go
  internal/infrastructure/runner/runner.go
  internal/ir/ratelimit_infra.go
  internal/ir/zz_generated.deepcopy.go
  internal/message/types.go
Labels: enhancement, area/infra-mgr, refactor
