Repository envoyproxy/gateway, pull requests merged in 2024-11, with the labels that each got.

#4601 fix keycloak ipv6 issue
  test/e2e/testdata/oidc-keycloak.yaml
Labels: cherrypick/release-v1.2

#4592 fix: Route with multiple parents has incorrect namespace in parentRef status
  internal/gatewayapi/contexts.go
  internal/gatewayapi/testdata/httproute-with-multiple-gateways-from-different-ns.in.yaml
  internal/gatewayapi/testdata/httproute-with-multiple-gateways-from-different-ns.out.yaml
  internal/gatewayapi/testdata/httproute-with-multiple-gateways-from-same-ns.in.yaml
  internal/gatewayapi/testdata/httproute-with-multiple-gateways-from-same-ns.out.yaml
  release-notes/current.yaml
Labels: cherrypick/release-v1.2

#4588 add envoy-gateway binary to release artifacts
  .github/workflows/latest_release.yaml
  .github/workflows/release.yaml
Labels: cherrypick/release-v1.2

#4587 fix: HTTPRoute status only shows one parent when targeting multiple Gateways from different GatewayClasses
  internal/gatewayapi/helpers.go
  internal/provider/kubernetes/status.go
  internal/provider/kubernetes/status_test.go
  release-notes/current.yaml
Labels: cherrypick/release-v1.2

#4583 direct response docs and tests
  internal/gatewayapi/route.go
  internal/gatewayapi/testdata/httproute-with-direct-response.in.yaml
  internal/gatewayapi/testdata/httproute-with-direct-response.out.yaml
  site/content/en/latest/tasks/traffic/direct-response.md
  test/e2e/testdata/direct-response.yaml
  test/e2e/tests/direct-response.go
  test/e2e/tests/response-override.go
Labels: cherrypick/release-v1.2

#4576 e2e: move apps to examples and pre-built
  examples/envoy-als/Dockerfile
  examples/envoy-als/Makefile
  examples/envoy-als/go.mod
  examples/envoy-als/go.sum
  examples/envoy-als/main.go
  examples/grpc-ext-auth/Dockerfile
  examples/grpc-ext-auth/Makefile
  examples/grpc-ext-auth/go.mod
  examples/grpc-ext-auth/go.sum
  examples/grpc-ext-auth/main.go
  examples/grpc-ext-proc/Dockerfile
  examples/grpc-ext-proc/Makefile
  examples/grpc-ext-proc/go.mod
  examples/grpc-ext-proc/go.sum
  examples/grpc-ext-proc/main.go
  examples/http-ext-auth/Dockerfile
  examples/http-ext-auth/Makefile
  examples/http-ext-auth/http-ext-auth.js
  examples/preserve-case-backend/Dockerfile
  examples/preserve-case-backend/Makefile
  examples/preserve-case-backend/go.mod
  examples/preserve-case-backend/go.sum
  examples/preserve-case-backend/main.go
  test/e2e/base/manifests.yaml
  test/e2e/testdata/accesslog-als.yaml
  test/e2e/testdata/ext-auth-grpc-service.yaml
  test/e2e/testdata/ext-auth-http-service.yaml
  test/e2e/testdata/ext-proc-service.yaml
  test/e2e/testdata/preserve-case.yaml
  test/e2e/tests/preservecase.go
  tools/make/common.mk
  tools/make/examples.mk
  tools/make/kube.mk
Labels: cherrypick/release-v1.2

#4623 fix: wasm oci image source e2e test failed when IP_FAMILY=ipv6
  test/e2e/tests/wasm_oci.go
Labels: cherrypick/release-v1.2

#4603 workaroud for the flaky oidc e2e test
  test/e2e/tests/oidc-backendcluster.go
  test/e2e/tests/oidc.go
Labels: cherrypick/release-v1.2

#4628 add docker.io registry name in image name
  api/v1alpha1/shared_types.go
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/component-level.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/custom.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/default-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/default.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/disable-prometheus.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/extension-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/override-labels-and-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/patch-daemonset.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/shutdown-manager.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/volumes.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-concurrency.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-extra-args.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-image-pull-secrets.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-name.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-node-selector.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-topology-spread-constraints.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/custom.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/custom_with_initcontainers.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/default-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/disable-prometheus.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/extension-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/override-labels-and-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/patch-deployment.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/shutdown-manager.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/volumes.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-concurrency.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-empty-memory-limits.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-extra-args.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-image-pull-secrets.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-name.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-node-selector.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-topology-spread-constraints.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/disable-prometheus.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/enable-tracing-custom.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/enable-tracing.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/merge-annotations.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/merge-labels.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/patch-deployment.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/with-node-selector.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/with-topology-spread-constraints.yaml
Labels: cherrypick/release-v1.2

#4525 e2e: use grafana alloy instead of fluent-bit
  charts/gateway-addons-helm/Chart.lock
  charts/gateway-addons-helm/Chart.yaml
  charts/gateway-addons-helm/README.md
  charts/gateway-addons-helm/values.yaml
  site/content/en/latest/install/gateway-addons-helm-api.md
  site/content/zh/latest/install/gateway-addons-helm-api.md
  test/e2e/tests/accesslog.go
  test/helm/gateway-addons-helm/e2e.in.yaml
  test/helm/gateway-addons-helm/e2e.out.yaml
  tools/make/kube.mk
Labels: cherrypick/release-v1.2, area/IPv6

#4636 fix: push a helm chart without v in ther version
  .github/workflows/build_and_test.yaml
  .github/workflows/release.yaml
  release-notes/current.yaml
Labels: cherrypick/release-v1.2

#4630 fix: BackendTlsPolicy specify multiple targetRefs of the same service, only one will work
  internal/gatewayapi/backendtlspolicy.go
  internal/gatewayapi/testdata/backendtlspolicy-multiple-targets.in.yaml
  internal/gatewayapi/testdata/backendtlspolicy-multiple-targets.out.yaml
  release-notes/current.yaml
Labels: cherrypick/release-v1.2, cherrypick/release-v1.1.4

#4650 Release News for v1.2.0
  site/content/en/news/releases/_index.md
  site/content/en/news/releases/notes/v1.2.0.md
  site/content/en/news/releases/v1.2.md
Labels: documentation

#4647 fix panic in provider when the direct response body is nil
  internal/provider/kubernetes/filters.go
  test/e2e/testdata/direct-response.yaml
  test/e2e/tests/direct-response.go
  test/e2e/tests/response-override.go
Labels: cherrypick/release-v1.2

#4648 update concepts to include reference to HTTPRouteFilter
  site/content/en/docs/concepts/concepts_overview.md
  site/content/en/latest/concepts/concepts_overview.md
  site/content/en/v1.2/concepts/concepts_overview.md
  site/static/img/envoy-gateway-resources-overview.png
Labels: documentation

#4649 rm timeout section from direct response docs
  site/content/en/docs/tasks/traffic/direct-response.md
  site/content/en/latest/tasks/traffic/direct-response.md
  site/content/en/v1.2/tasks/traffic/direct-response.md
Labels: documentation

#4651 docs: update upgrade notes
  site/content/en/docs/install/install-helm.md
  site/content/en/docs/install/install-yaml.md
  site/content/en/latest/install/install-helm.md
  site/content/en/latest/install/install-yaml.md
  site/content/en/v1.2/install/install-helm.md
  site/content/en/v1.2/install/install-yaml.md
Labels: documentation

#4674 add link to install EG in release news
  site/content/en/news/releases/v1.2.md
Labels: documentation

#4675 docs: add a note of helm not updating CRDs in the upgrade section
  site/content/en/docs/install/install-helm.md
  site/content/en/latest/install/install-helm.md
  site/content/en/v1.2/install/install-helm.md
Labels: documentation

#4705 fix: remove backendrefs validation
  api/v1alpha1/ext_auth_types.go
  charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
  internal/gatewayapi/securitypolicy.go
  internal/gatewayapi/testdata/securitypolicy-with-extauth-backend.in.yaml
  internal/gatewayapi/testdata/securitypolicy-with-extauth-backend.out.yaml
  release-notes/current.yaml
  test/cel-validation/securitypolicy_test.go
  test/e2e/testdata/ext-auth-http-securitypolicy.yaml
Labels: cherrypick/release-v1.2.2

#4518 doc: add standalone deployment doc
  examples/standalone/quickstart.yaml
  site/content/en/docs/tasks/operations/standalone-deployment-mode.md
  site/content/en/latest/tasks/operations/standalone-deployment-mode.md
  site/content/en/v1.2/tasks/operations/standalone-deployment-mode.md
Labels: documentation, area/standalone

#4681 fix: tcp listener is rejected when no route attached
  internal/xds/translator/testdata/in/extension-xds-ir/extensionpolicy-tcp-udp-http.yaml
  internal/xds/translator/testdata/in/xds-ir/listener-connection-limit.yaml
  internal/xds/translator/testdata/in/xds-ir/listener-tcp-keepalive.yaml
  internal/xds/translator/testdata/in/xds-ir/listener-tcp-without-route.yaml
  internal/xds/translator/testdata/in/xds-ir/tcp-endpoint-stats.yaml
  internal/xds/translator/testdata/in/xds-ir/tcp-req-resp-sizes-stats.yaml
  internal/xds/translator/testdata/out/extension-xds-ir/extensionpolicy-tcp-udp-http.clusters.yaml
  internal/xds/translator/testdata/out/extension-xds-ir/extensionpolicy-tcp-udp-http.endpoints.yaml
  internal/xds/translator/testdata/out/extension-xds-ir/extensionpolicy-tcp-udp-http.listeners.yaml
  internal/xds/translator/testdata/out/extension-xds-ir/extensionpolicy-tcp-udp-http.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/listener-connection-limit.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/listener-connection-limit.endpoints.yaml
  internal/xds/translator/testdata/out/xds-ir/listener-connection-limit.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/listener-tcp-keepalive.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/listener-tcp-keepalive.endpoints.yaml
  internal/xds/translator/testdata/out/xds-ir/listener-tcp-keepalive.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/listener-tcp-without-route.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/listener-tcp-without-route.endpoints.yaml
  internal/xds/translator/testdata/out/xds-ir/listener-tcp-without-route.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/listener-tcp-without-route.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/tcp-endpoint-stats.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/tcp-endpoint-stats.endpoints.yaml
  internal/xds/translator/testdata/out/xds-ir/tcp-endpoint-stats.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/tcp-req-resp-sizes-stats.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/tcp-req-resp-sizes-stats.endpoints.yaml
  internal/xds/translator/testdata/out/xds-ir/tcp-req-resp-sizes-stats.listeners.yaml
  internal/xds/translator/translator.go
  release-notes/current.yaml
Labels: cherrypick/release-v1.2.2

#4707 fix: translator reports errors for existing clusters and secretes
  internal/gatewayapi/envoyextensionpolicy.go
  internal/gatewayapi/ext_service.go
  internal/gatewayapi/securitypolicy.go
  internal/gatewayapi/testdata/envoyextensionpolicy-override-replace.out.yaml
  internal/gatewayapi/testdata/envoyextensionpolicy-with-extproc-with-backendtlspolicy.out.yaml
  internal/gatewayapi/testdata/envoyextensionpolicy-with-extproc-with-multiple-backendrefs.out.yaml
  internal/gatewayapi/testdata/envoyextensionpolicy-with-extproc-with-traffic-features.out.yaml
  internal/gatewayapi/testdata/envoyproxy-priority-backend.out.yaml
  internal/gatewayapi/testdata/securitypolicy-with-extauth-backend.out.yaml
  internal/gatewayapi/testdata/securitypolicy-with-extauth-backendref.out.yaml
  internal/gatewayapi/testdata/securitypolicy-with-extauth-recomputation.out.yaml
  internal/gatewayapi/testdata/securitypolicy-with-extauth-with-backendtlspolicy.out.yaml
  internal/gatewayapi/testdata/securitypolicy-with-extauth.out.yaml
  internal/gatewayapi/testdata/securitypolicy-with-oidc-backendcluster.out.yaml
  internal/xds/translator/accesslog.go
  internal/xds/translator/extauth.go
  internal/xds/translator/extproc.go
  internal/xds/translator/oidc.go
  internal/xds/translator/ratelimit.go
  internal/xds/translator/testdata/in/xds-ir/securitypolicy-with-oidc-jwt-authz.yaml
  internal/xds/translator/testdata/out/xds-ir/securitypolicy-with-oidc-jwt-authz.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/securitypolicy-with-oidc-jwt-authz.endpoints.yaml
  internal/xds/translator/testdata/out/xds-ir/securitypolicy-with-oidc-jwt-authz.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/securitypolicy-with-oidc-jwt-authz.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/securitypolicy-with-oidc-jwt-authz.secrets.yaml
  internal/xds/translator/tracing.go
  internal/xds/translator/translator.go
  internal/xds/translator/utils.go
  release-notes/current.yaml
Labels: cherrypick/release-v1.2.2

#4515 api: support disable ALPN in CTP
  api/v1alpha1/tls_types.go
  charts/gateway-helm/crds/generated/gateway.envoyproxy.io_clienttrafficpolicies.yaml
  charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
  internal/gatewayapi/clienttrafficpolicy.go
  internal/gatewayapi/testdata/clienttrafficpolicy-tls-settings.in.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-tls-settings.out.yaml
  release-notes/current.yaml
  site/content/en/latest/api/extension_types.md
  site/content/zh/latest/api/extension_types.md
Labels: release-note

#4754 Fix: frequent 503 errors when connecting to a Service experiencing high Pod churn
  internal/provider/kubernetes/status_updater.go
  release-notes/current.yaml
Labels: cherrypick/release-v1.1.4, cherrypick/release-v1.2.2

#4801 xds: use `::1` if IPFamily is IPv6 on admin server
  internal/infrastructure/common/proxy_args.go
  internal/infrastructure/kubernetes/proxy/resource_provider_test.go
  internal/infrastructure/kubernetes/proxy/testdata/deployments/ipv6.yaml
  internal/xds/bootstrap/bootstrap.go
  internal/xds/bootstrap/bootstrap_test.go
  internal/xds/bootstrap/testdata/render/ipv6.yaml
Labels: cherrypick/release-v1.2.3

#4802 fix: remove the default retry policy for jwks fetch
  internal/cmd/egctl/testdata/translate/out/jwt-single-route-single-match-to-xds.all.json
  internal/cmd/egctl/testdata/translate/out/jwt-single-route-single-match-to-xds.all.yaml
  internal/cmd/egctl/testdata/translate/out/jwt-single-route-single-match-to-xds.listener.yaml
  internal/xds/translator/jwt.go
  internal/xds/translator/testdata/out/xds-ir/authorization-jwt-claim.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/authorization-jwt-scope.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/custom-filter-order.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/jwt-custom-extractor.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/jwt-multi-route-multi-provider.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/jwt-multi-route-single-provider.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/jwt-optional.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/jwt-ratelimit.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/jwt-single-route-single-match.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/securitypolicy-with-oidc-jwt-authz.listeners.yaml
  release-notes/current.yaml
Labels: cherrypick/release-v1.2.3
