Repository envoyproxy/gateway, pull requests merged in 2024-08, with the labels that each got.

#4021 reduce readinessProbe failureThreshold and periodSeconds
  internal/infrastructure/kubernetes/proxy/resource.go
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/component-level.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/custom.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/default-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/default.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/disable-prometheus.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/extension-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/override-labels-and-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/patch-daemonset.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/shutdown-manager.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/volumes.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-concurrency.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-extra-args.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-image-pull-secrets.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-name.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-node-selector.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-topology-spread-constraints.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/custom.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/custom_with_initcontainers.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/default-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/disable-prometheus.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/extension-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/override-labels-and-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/patch-deployment.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/shutdown-manager.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/volumes.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-concurrency.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-empty-memory-limits.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-extra-args.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-image-pull-secrets.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-name.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-node-selector.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-topology-spread-constraints.yaml
  internal/infrastructure/kubernetes/ratelimit/resource.go
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/custom.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default-env.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/disable-prometheus.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/enable-tracing-custom.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/enable-tracing.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/extension-env.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/override-env.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/patch-deployment.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/redis-tls-settings.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/tolerations.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/volumes.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/with-node-selector.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/with-topology-spread-constraints.yaml
Labels: cherrypick/release-v1.0.3, cherrypick/release-v1.1.1

#4000 feat: gateway http listener isolation
  internal/gatewayapi/conformance/suite.go
  internal/gatewayapi/helpers.go
  internal/gatewayapi/route.go
  internal/gatewayapi/testdata/gateway-http-listener-with-hostname-intersection.in.yaml
  internal/gatewayapi/testdata/gateway-http-listener-with-hostname-intersection.out.yaml
  internal/gatewayapi/tls.go
Labels: cherrypick/release-v1.0.3, cherrypick/release-v1.1.1

#4073 fix ratelimit statsd not working
  internal/infrastructure/kubernetes/ratelimit/resource.go
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/custom.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default-env.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/default.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/disable-prometheus.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/enable-tracing-custom.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/enable-tracing.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/extension-env.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/override-env.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/patch-deployment.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/redis-tls-settings.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/tolerations.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/volumes.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/with-node-selector.yaml
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/with-topology-spread-constraints.yaml
Labels: cherrypick/release-v1.0.3, cherrypick/release-v1.1.1

#4090 fix: active http healthcheck documents a default for expected status, but doesn't use it
  internal/gatewayapi/clustersettings.go
  internal/gatewayapi/testdata/backendtrafficpolicy-with-healthcheck.in.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-healthcheck.out.yaml
Labels: cherrypick/release-v1.0.3, cherrypick/release-v1.1.1

#4017 add-nodeSelector
  charts/gateway-helm/README.md
  charts/gateway-helm/templates/envoy-gateway-deployment.yaml
  charts/gateway-helm/values.tmpl.yaml
  site/content/en/latest/install/gateway-helm-api.md
  site/content/zh/latest/install/gateway-helm-api.md
Labels: area/installation

#4095 fix: don't lose timeout settings that originate from the route when translating the backend traffic policy
  internal/gatewayapi/backendtrafficpolicy.go
  internal/gatewayapi/clustersettings.go
  internal/gatewayapi/route.go
  internal/gatewayapi/testdata/backendtrafficpolicy-with-httproute-timeout.in.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-httproute-timeout.out.yaml
  internal/gatewayapi/testdata/httproute-and-backendtrafficpolicy-with-timeout.out.yaml
Labels: cherrypick/release-v1.1.1
