Repository envoyproxy/gateway, pull requests merged in 2024-10, with the labels that each got.

#4270 [Gateway API 1.2.0] Upgrade Gateway API to 1.2.0-rc2
  charts/gateway-helm/crds/gatewayapi-crds.yaml
  examples/extension-server/go.mod
  examples/extension-server/go.sum
  go.mod
  go.sum
  internal/gatewayapi/conformance/suite.go
  internal/gatewayapi/conformance/support_level.go
  internal/gatewayapi/helpers.go
  internal/gatewayapi/route.go
  internal/gatewayapi/status/gatewayclass.go
  internal/gatewayapi/status/gatewayclass_test.go
  osv-scanner.toml
  test/e2e/e2e_test.go
  test/e2e/merge_gateways/merge_gateways_test.go
  test/e2e/multiple_gc/multiple_gc_test.go
  test/e2e/tests/eg_upgrade.go
  test/e2e/upgrade/eg_upgrade_test.go
Labels: release-note

#4293 feat(translator): client tls session resumption
  api/v1alpha1/tls_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/gateway-helm/crds/generated/gateway.envoyproxy.io_clienttrafficpolicies.yaml
  internal/gatewayapi/clienttrafficpolicy.go
  internal/gatewayapi/testdata/clienttrafficpolicy-tls-settings.in.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-tls-settings.out.yaml
  internal/ir/xds.go
  internal/xds/translator/listener.go
  internal/xds/translator/testdata/in/xds-ir/tls-with-ciphers-versions-alpn.yaml
  internal/xds/translator/testdata/out/xds-ir/http3.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/jsonpatch-with-jsonpath.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/jsonpatch.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/listener-proxy-protocol.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/mixed-tls-jwt-authn.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/multiple-listeners-same-port.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/mutual-tls-forward-client-certificate-with-custom-data.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/mutual-tls-forward-client-certificate.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/mutual-tls-required-client-certificate-disabled.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/mutual-tls.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/simple-tls.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/suppress-envoy-headers.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/tcp-route-tls-terminate.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/tls-with-ciphers-versions-alpn.listeners.yaml
  site/content/en/latest/api/extension_types.md
  site/content/en/latest/tasks/security/secure-gateways.md
  site/content/zh/latest/api/extension_types.md
  test/e2e/base/manifests.yaml
  test/e2e/testdata/client-mtls.yaml
  test/e2e/tests/client_mtls.go
Labels: release-note

#4290 helm: Remove default cpu limit inside chart
  charts/gateway-helm/README.md
  charts/gateway-helm/values.tmpl.yaml
  site/content/en/latest/install/gateway-helm-api.md
  site/content/zh/latest/install/gateway-helm-api.md
  test/helm/gateway-helm/certjen-custom-scheduling.out.yaml
  test/helm/gateway-helm/control-plane-with-pdb.out.yaml
  test/helm/gateway-helm/default-config.out.yaml
  test/helm/gateway-helm/deployment-custom-topology.out.yaml
  test/helm/gateway-helm/deployment-images-config.out.yaml
  test/helm/gateway-helm/deployment-priorityclass.out.yaml
  test/helm/gateway-helm/envoy-gateway-config.out.yaml
  test/helm/gateway-helm/global-images-config.out.yaml
  test/helm/gateway-helm/service-annotations.out.yaml
Labels: release-note

#4460 fix: disable ALPN for non-HTTP routes
  internal/gatewayapi/helpers.go
  internal/gatewayapi/listener.go
  internal/gatewayapi/testdata/backendtlspolicy-ca-only-secret.out.yaml
  internal/gatewayapi/testdata/backendtlspolicy-ca-only.out.yaml
  internal/gatewayapi/testdata/backendtlspolicy-default-ns-targetrefs.out.yaml
  internal/gatewayapi/testdata/backendtlspolicy-default-ns.out.yaml
  internal/gatewayapi/testdata/backendtlspolicy-system-truststore.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-http3.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-mtls-client-verification.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-mtls-forward-client-cert-custom-data.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-mtls-forward-client-cert.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-mtls.out.yaml
  internal/gatewayapi/testdata/envoyextensionpolicy-with-extproc-with-backendtlspolicy.out.yaml
  internal/gatewayapi/testdata/envoyextensionpolicy-with-extproc-with-multiple-backendrefs.out.yaml
  internal/gatewayapi/testdata/envoyextensionpolicy-with-extproc-with-traffic-features.out.yaml
  internal/gatewayapi/testdata/envoyproxy-priority-backend.out.yaml
  internal/gatewayapi/testdata/envoyproxy-tls-settings-invalid-ns.out.yaml
  internal/gatewayapi/testdata/envoyproxy-tls-settings-invalid.out.yaml
  internal/gatewayapi/testdata/envoyproxy-tls-settings.out.yaml
  internal/gatewayapi/testdata/gateway-infrastructure.out.yaml
  internal/gatewayapi/testdata/gateway-with-listener-with-tls-secret-in-other-namespace-allowed-by-refgrant.out.yaml
  internal/gatewayapi/testdata/gateway-with-listener-with-tls-terminate-and-passthrough.out.yaml
  internal/gatewayapi/testdata/gateway-with-listener-with-valid-multiple-tls-configuration-with-same-algorithm-different-fqdn.out.yaml
  internal/gatewayapi/testdata/gateway-with-listener-with-valid-multiple-tls-configuration.out.yaml
  internal/gatewayapi/testdata/gateway-with-listener-with-valid-tls-configuration.out.yaml
  internal/gatewayapi/testdata/gateway-with-stale-status-condition.out.yaml
  internal/gatewayapi/testdata/httproute-attaching-to-gateway-with-two-listeners-with-different-ports.out.yaml
  internal/gatewayapi/testdata/securitypolicy-with-extauth-with-backendtlspolicy.out.yaml
  internal/gatewayapi/testdata/tcproute-attaching-to-gateway-with-listener-tls-terminate.out.yaml
  internal/ir/xds.go
  internal/xds/translator/listener.go
  internal/xds/translator/testdata/in/xds-ir/mutual-tls-required-client-certificate-disabled.yaml
  internal/xds/translator/testdata/in/xds-ir/mutual-tls.yaml
  internal/xds/translator/testdata/in/xds-ir/tcp-route-tls-terminate.yaml
  internal/xds/translator/testdata/out/xds-ir/mutual-tls-required-client-certificate-disabled.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/mutual-tls.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/tcp-route-tls-terminate.listeners.yaml
  internal/xds/translator/translator.go
Labels: release-note

#4548 e2e test for Gateway with EnvoyProxy
  internal/provider/kubernetes/controller.go
  test/e2e/testdata/gateway-with-envoyproxy.yaml
  test/e2e/tests/gatewayt-with-envoyproxy.go
Labels: cherrypick/release-v1.2

#4519 make watching alpha CRDs optional
  internal/provider/kubernetes/controller.go
  internal/provider/kubernetes/predicates.go
  internal/provider/kubernetes/predicates_test.go
  internal/provider/kubernetes/routes.go
Labels: cherrypick/release-v1.2

#4499 fix: validate proto messages before converting them to anypb.Any
  internal/utils/protocov/protocov.go
  internal/xds/translator/accesslog.go
  internal/xds/translator/authorization.go
  internal/xds/translator/basicauth.go
  internal/xds/translator/cluster.go
  internal/xds/translator/custom_response.go
  internal/xds/translator/fault.go
  internal/xds/translator/jwt.go
  internal/xds/translator/listener.go
  internal/xds/translator/listener_test.go
  internal/xds/translator/oidc.go
  internal/xds/translator/testdata/in/xds-ir/accesslog-without-format.yaml
  internal/xds/translator/testdata/in/xds-ir/accesslog.yaml
  internal/xds/translator/testdata/in/xds-ir/authorization-multiple-principals.yaml
  internal/xds/translator/testdata/out/xds-ir/accesslog-without-format.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/accesslog.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/authorization-multiple-principals.routes.yaml
  internal/xds/translator/tracing.go
  internal/xds/translator/translator.go
Labels: cherrypick/release-v1.1, cherrypick/release-v1.2

#4547 Fix: xds translation failed when wasm http code source configured without sha
  internal/gatewayapi/envoyextensionpolicy.go
  internal/gatewayapi/testdata/custom-filter-order.in.yaml
  internal/gatewayapi/testdata/custom-filter-order.out.yaml
  internal/gatewayapi/testdata/envoyextensionpolicy-with-wasm-targetrefs.in.yaml
  internal/gatewayapi/testdata/envoyextensionpolicy-with-wasm-targetrefs.out.yaml
  internal/gatewayapi/testdata/envoyextensionpolicy-with-wasm.in.yaml
  internal/gatewayapi/testdata/envoyextensionpolicy-with-wasm.out.yaml
  internal/gatewayapi/translator_test.go
  release-notes/current.yaml
  test/e2e/testdata/wasm-http.yaml
  test/e2e/tests/wasm_http.go
Labels: cherrypick/release-v1.1, cherrypick/release-v1.2

#4580 fix egctl release artifacts
  .github/workflows/release.yaml
  tools/make/kube.mk
Labels: cherrypick/release-v1.1.3, cherrypick/release-v1.2

#4584 fix debug level logging for IR
  internal/gatewayapi/runner/runner.go
Labels: cherrypick/release-v1.2

#4581 fix: trigger reconcile for Secret updates referenced by a BackendTLSP…
  internal/provider/kubernetes/indexers.go
  internal/provider/kubernetes/predicates.go
Labels: cherrypick/release-v1.1.3, cherrypick/release-v1.2
