Repository envoyproxy/gateway, pull requests merged in 2024-07, with the labels that each got.

#3677 e2e: Add backend health check e2e case via active http
  test/e2e/testdata/backend-health-check-active-http.yaml
  test/e2e/tests/backend_health_check.go
Labels: area/testing

#3816 e2e: make sure ALS server is ready
  test/e2e/tests/accesslog.go
  test/e2e/tests/utils.go
Labels: cherrypick/release-v1.1

#3796 docs: add task for wasm extensions
  site/content/en/latest/tasks/extensibility/wasm.md
Labels: documentation

#3835 fix: backendtls minversion
  internal/gatewayapi/backendtlspolicy.go
Labels: cherrypick/release-v1.1

#3839 fix: backendtls client cert
  internal/xds/translator/testdata/in/xds-ir/http-route-with-clientcert.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-clientcert.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-clientcert.endpoints.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-clientcert.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-clientcert.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-clientcert.secrets.yaml
  internal/xds/translator/translator.go
Labels: cherrypick/release-v1.1

#3771 fix: prevent xdsIR updates from overwriting RateLimit configs from other xdsIR
  internal/globalratelimit/runner/runner.go
  internal/globalratelimit/runner/runner_test.go
Labels: cherrypick/release-v1.1

#3869 return 500 error for failed SecurityPolicies to avoid unauthorized access to xRoutes
  internal/gatewayapi/securitypolicy.go
  internal/gatewayapi/testdata/securitypolicy-with-extauth-invalid-no-matching-port.out.yaml
  internal/gatewayapi/testdata/securitypolicy-with-extauth-invalid-no-port.out.yaml
  internal/gatewayapi/testdata/securitypolicy-with-extauth-invalid-no-reference-grant.out.yaml
  internal/gatewayapi/testdata/securitypolicy-with-extauth-invalid-no-service.out.yaml
  internal/gatewayapi/testdata/securitypolicy-with-jwt-and-invalid-oidc.out.yaml
  test/e2e/testdata/securitypolicy-translation-failed.yaml
  test/e2e/tests/securitypolicy_transaltion_failed.go
  test/e2e/tests/utils.go
Labels: cherrypick/release-v1.0, cherrypick/release-v1.1

#3881 fix override issue for EEP
  internal/gatewayapi/envoyextensionpolicy.go
  internal/gatewayapi/testdata/backend-invalid-feature-disabled.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-override-replace.in.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-override-replace.out.yaml
  internal/gatewayapi/testdata/custom-filter-order.out.yaml
  internal/gatewayapi/testdata/envoyextensionpolicy-override-replace.in.yaml
  internal/gatewayapi/testdata/envoyextensionpolicy-override-replace.out.yaml
  internal/gatewayapi/testdata/envoyextensionpolicy-status-conditions.out.yaml
  internal/gatewayapi/testdata/envoyextensionpolicy-with-extproc-with-backendtlspolicy.out.yaml
  internal/gatewayapi/testdata/envoyextensionpolicy-with-extproc-with-multiple-backendrefs.out.yaml
  internal/gatewayapi/testdata/envoyextensionpolicy-with-wasm-targetrefs.out.yaml
  internal/gatewayapi/testdata/envoyextensionpolicy-with-wasm.out.yaml
  internal/gatewayapi/testdata/securitypolicy-override-replace.in.yaml
  internal/gatewayapi/testdata/securitypolicy-override-replace.out.yaml
  internal/ir/xds.go
  internal/ir/zz_generated.deepcopy.go
  internal/xds/translator/extproc.go
  internal/xds/translator/testdata/in/xds-ir/custom-filter-order.yaml
  internal/xds/translator/testdata/in/xds-ir/ext-proc.yaml
  internal/xds/translator/testdata/in/xds-ir/wasm.yaml
  internal/xds/translator/wasm.go
Labels: cherrypick/release-v1.1

#3885 accesslog: fix different CelMatches on AccessLog
  api/v1alpha1/accesslogging_types.go
  internal/gatewayapi/listener.go
  internal/gatewayapi/testdata/envoyproxy-accesslog-cel.in.yaml
  internal/gatewayapi/testdata/envoyproxy-accesslog-cel.out.yaml
  internal/gatewayapi/testdata/envoyproxy-accesslog-without-format.out.yaml
  internal/ir/xds.go
  internal/ir/zz_generated.deepcopy.go
  internal/xds/translator/accesslog.go
  internal/xds/translator/testdata/in/xds-ir/accesslog-cel.yaml
  internal/xds/translator/testdata/in/xds-ir/accesslog-multi-cel.yaml
  test/e2e/tests/utils.go
  tools/make/kube.mk
Labels: cherrypick/release-v1.1

#3878 rm gateway-api translation error message from direct response
  internal/gatewayapi/filters.go
  internal/ir/xds.go
  internal/ir/xds_test.go
  internal/ir/zz_generated.deepcopy.go
  internal/xds/translator/route.go
  internal/xds/translator/testdata/out/xds-ir/accesslog-cel.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/accesslog-endpoint-stats.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/accesslog-formatters.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/accesslog-multi-cel.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/accesslog-without-format.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/accesslog.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-direct-response.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/tracing-endpoint-stats.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/tracing-zipkin.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/tracing.routes.yaml
Labels: cherrypick/release-v1.0, cherrypick/release-v1.1

#3876 GetParentReferences should use namespace from RouteContext
  internal/gatewayapi/helpers.go
  internal/gatewayapi/helpers_test.go
  internal/gatewayapi/route.go
  internal/gatewayapi/testdata/httproute-with-multi-gateways-notmatch.in.yaml
  internal/gatewayapi/testdata/httproute-with-multi-gateways-notmatch.out.yaml
  internal/gatewayapi/testdata/httproute-with-multi-gateways-with-same-name.in.yaml
  internal/gatewayapi/testdata/httproute-with-multi-gateways-with-same-name.out.yaml
Labels: cherrypick/release-v1.0, cherrypick/release-v1.1
