Repository envoyproxy/gateway, pull requests merged in 2024-04, with the labels that each got.

#3057 Set host for http health checker explicitly to avoid using the cluster name as host header for http health checking request.
  internal/gatewayapi/backendtrafficpolicy.go
  internal/gatewayapi/testdata/backendtrafficpolicy-with-healthcheck.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-tcp-udp-listeners-apply-on-gateway.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-tcp-udp-listeners-apply-on-route.out.yaml
  internal/ir/xds.go
  internal/ir/xds_test.go
  internal/xds/translator/cluster.go
  internal/xds/translator/testdata/in/xds-ir/health-check.yaml
  internal/xds/translator/testdata/out/xds-ir/health-check.clusters.yaml
Labels: cherrypick/release-v1.0

#2579 Change route sorting order to Exact > RegularExpression > PathPrefix
  internal/gatewayapi/sort.go
  internal/gatewayapi/testdata/grpcroute-with-service-match.out.yaml
Labels: cherrypick/release-v1.0

#3061 fix: infraIR duplicate port translation for merged gateways
  internal/gatewayapi/listener.go
  internal/gatewayapi/testdata/conflicting-policies.out.yaml
  internal/gatewayapi/testdata/merge-valid-multiple-gateways-multiple-listeners-same-ports.in.yaml
  internal/gatewayapi/testdata/merge-valid-multiple-gateways-multiple-listeners-same-ports.out.yaml
Labels: cherrypick/release-v1.0

#3102 translator: set SpawnUpstreamSpan to true
  internal/xds/translator/testdata/out/xds-ir/tracing.listeners.yaml
  internal/xds/translator/tracing.go
Labels: cherrypick/release-v1.0

#3085 fix: rate limit doesn't work with two(and more) listeners
  internal/xds/translator/ratelimit.go
  internal/xds/translator/testdata/out/ratelimit-config/distinct-match.yaml
  internal/xds/translator/testdata/out/ratelimit-config/distinct-remote-address-match.yaml
  internal/xds/translator/testdata/out/ratelimit-config/empty-header-matches.yaml
  internal/xds/translator/testdata/out/ratelimit-config/masked-remote-address-match.yaml
  internal/xds/translator/testdata/out/ratelimit-config/multiple-masked-remote-address-match-with-same-cidr.yaml
  internal/xds/translator/testdata/out/ratelimit-config/multiple-matches.yaml
  internal/xds/translator/testdata/out/ratelimit-config/multiple-routes.yaml
  internal/xds/translator/testdata/out/ratelimit-config/multiple-rules.yaml
  internal/xds/translator/testdata/out/ratelimit-config/value-match.yaml
  test/e2e/testdata/ratelimit-multiple-listeners.yaml
  test/e2e/tests/ratelimit.go
Labels: cherrypick/release-v1.0

#2739 fix: remove no needed new pointer creation
  internal/gatewayapi/runner/runner.go
Labels: hold

#2849 docs: support notImplementedHide
  api/v1alpha1/backendtrafficpolicy_types.go
  site/content/en/latest/api/extension_types.md
  tools/crd-ref-docs/config.yaml
  tools/crd-ref-docs/templates/type.tpl
  tools/src/crd-ref-docs/go.mod
  tools/src/crd-ref-docs/go.sum
Labels: documentation

#3087 api: ext-proc timeout, fail-open, backendRefs
  api/v1alpha1/ext_proc_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml
  site/content/en/latest/api/extension_types.md
  test/cel-validation/envoyextensionpolicy_test.go
Labels: area/api
