Repository envoyproxy/gateway, pull requests merged in 2024-09, with the labels that each got.

#4009 API: authorization api for jwt claims
  api/v1alpha1/authorization_types.go
  api/v1alpha1/securitypolicy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
  site/content/en/latest/api/extension_types.md
  site/content/zh/latest/api/extension_types.md
  test/cel-validation/securitypolicy_test.go
Labels: area/api

#4209 fix: reject invalid backends in route validation
  internal/gatewayapi/testdata/httproute-attaching-to-listener-with-backend-backendref.out.yaml
  internal/gatewayapi/validate.go
Labels: cherrypick/release-v1.1.1

#4204 fix: allow empty slowStart when using LeastRequest
  internal/gatewayapi/clustersettings.go
  internal/xds/translator/cluster.go
Labels: cherrypick/release-v1.0.3, cherrypick/release-v1.1.1

#4271 OIDC: add nonce support to the oauth2 filter
  examples/extension-server/go.mod
  examples/extension-server/go.sum
  go.mod
  go.sum
  internal/xds/extensions/extensions.gen.go
  internal/xds/translator/oidc.go
  internal/xds/translator/testdata/out/xds-ir/multiple-listeners-same-port-with-different-filters.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/oidc.listeners.yaml
Labels: envoy-release-dependency

#4279 fix: Reconcile on HTTPRoute labels change
  internal/provider/kubernetes/controller.go
Labels: cherrypick/release-v1.1.2

#4296 fix: handle invalid sectionName in BackendTLSPolicy for Backend
  internal/gatewayapi/backendtlspolicy.go
  internal/gatewayapi/testdata/backendtlspolicy-default-ns.in.yaml
  internal/gatewayapi/testdata/backendtlspolicy-default-ns.out.yaml
Labels: cherrypick/release-v1.1.2

#4288 revisit envoy shutdown settings
  api/v1alpha1/envoyproxy_types.go
  charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
  internal/cmd/envoy.go
  internal/infrastructure/kubernetes/proxy/resource.go
  internal/infrastructure/kubernetes/proxy/resource_provider.go
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/component-level.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/custom.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/default-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/default.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/disable-prometheus.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/extension-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/override-labels-and-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/patch-daemonset.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/volumes.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-concurrency.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-extra-args.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-image-pull-secrets.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-name.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-node-selector.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-topology-spread-constraints.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/custom.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/custom_with_initcontainers.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/default-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/disable-prometheus.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/extension-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/override-labels-and-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/patch-deployment.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/volumes.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-concurrency.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-empty-memory-limits.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-extra-args.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-image-pull-secrets.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-name.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-node-selector.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-topology-spread-constraints.yaml
  site/content/en/latest/api/extension_types.md
  site/content/zh/latest/api/extension_types.md
Labels: release-note

#4295 [release/v1.0] Bump Envoy Proxy to v1.29.9
  api/v1alpha1/shared_types.go
  internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/disable-prometheus.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/override-labels-and-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/patch-deployment.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/shutdown-manager.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-concurrency.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-extra-args.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-image-pull-secrets.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-node-selector.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-topology-spread-constraints.yaml
Labels: cherrypick/release-v1.0.3

#4294 [release/v1.1] Bump EnvoyProxy to v1.32.2
  api/v1alpha1/shared_types.go
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/component-level.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/default.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/disable-prometheus.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/override-labels-and-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/patch-daemonset.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/shutdown-manager.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-concurrency.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-extra-args.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-image-pull-secrets.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-name.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-node-selector.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-topology-spread-constraints.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/disable-prometheus.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/override-labels-and-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/patch-deployment.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/shutdown-manager.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-concurrency.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-empty-memory-limits.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-extra-args.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-image-pull-secrets.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-name.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-node-selector.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-topology-spread-constraints.yaml
Labels: cherrypick/release-v1.1.2
