Repository envoyproxy/gateway, pull requests merged in 2024-03, with the labels that each got.

#2704 fix(helm): refactor monitoring service
  charts/gateway-helm/templates/envoy-gateway-deployment.yaml
  charts/gateway-helm/templates/envoy-gateway-metrics-service.yaml
  charts/gateway-helm/values.tmpl.yaml
  site/content/en/latest/install/api.md
Labels: area/installation, area/observability, road-to-ga

#2247 Add Upstream TLS Support
  charts/gateway-helm/templates/_rbac.tpl
  internal/gatewayapi/backendtlspolicy.go
  internal/gatewayapi/resource.go
  internal/gatewayapi/route.go
  internal/gatewayapi/runner/runner.go
  internal/gatewayapi/testdata/backendtlspolicy-ca-only.in.yaml
  internal/gatewayapi/testdata/backendtlspolicy-ca-only.out.yaml
  internal/gatewayapi/testdata/backendtlspolicy-default-ns.in.yaml
  internal/gatewayapi/testdata/backendtlspolicy-default-ns.out.yaml
  internal/gatewayapi/testdata/backendtlspolicy-invalid-ca.in.yaml
  internal/gatewayapi/testdata/backendtlspolicy-invalid-ca.out.yaml
  internal/gatewayapi/translator.go
  internal/gatewayapi/zz_generated.deepcopy.go
  internal/ir/xds.go
  internal/ir/zz_generated.deepcopy.go
  internal/message/types.go
  internal/provider/kubernetes/controller.go
  internal/provider/kubernetes/indexers.go
  internal/provider/kubernetes/predicates.go
  internal/provider/kubernetes/status.go
  internal/status/backendtlspolicy.go
  internal/status/status.go
  internal/xds/translator/testdata/in/xds-ir/http-route-with-tlsbundle.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-tlsbundle.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-tlsbundle.endpoints.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-tlsbundle.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-tlsbundle.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-tlsbundle.secrets.yaml
  internal/xds/translator/translator.go
  internal/xds/translator/translator_test.go
Labels: road-to-ga

#2730 Adding OIDC e2e tests and Relaxing HTTPS restriction for OIDC token endpoint
  go.mod
  internal/gatewayapi/securitypolicy.go
  internal/xds/translator/jwt.go
  internal/xds/translator/oidc.go
  internal/xds/translator/utils.go
  test/e2e/testdata/oidc-keycloak.yaml
  test/e2e/testdata/oidc-securitypolicy.yaml
  test/e2e/tests/basic_auth.go
  test/e2e/tests/local_ratelimit.go
  test/e2e/tests/oidc-testclient.go
  test/e2e/tests/oidc.go
  test/e2e/tests/utils.go
Labels: road-to-ga

#2768 Fix hmac secret
  internal/crypto/certgen.go
  internal/crypto/certgen_test.go
  internal/gatewayapi/runner/runner.go
  internal/gatewayapi/securitypolicy.go
  internal/gatewayapi/testdata/securitypolicy-with-oidc.in.yaml
  internal/gatewayapi/testdata/securitypolicy-with-oidc.out.yaml
  internal/gatewayapi/translator.go
  internal/gatewayapi/translator_test.go
  internal/ir/xds.go
  internal/ir/zz_generated.deepcopy.go
  internal/provider/kubernetes/controller.go
  internal/provider/kubernetes/predicates.go
  internal/provider/kubernetes/secrets.go
  internal/xds/translator/oidc.go
Labels: road-to-ga

#2785 fix: add missing release notes details and re organize it
  release-notes/v1.0.0-rc.1.yaml
Labels: cherrypick/release-v1.0

#2725 e2e: backend upgrade test
  go.mod
  go.sum
  test/e2e/testdata/backend-upgrade.yaml
  test/e2e/tests/backend-upgrade.go
Labels: road-to-ga

#2782 fix: Delete unused status keys from watchable
  internal/gatewayapi/runner/runner.go
  internal/gatewayapi/runner/runner_test.go
  internal/xds/translator/runner/runner.go
  internal/xds/translator/runner/runner_test.go
Labels: road-to-ga

#2815 remove: support for hostnetwork
  api/v1alpha1/shared_types.go
  charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
  internal/infrastructure/kubernetes/proxy/resource_provider.go
  internal/infrastructure/kubernetes/proxy/resource_provider_test.go
  internal/infrastructure/kubernetes/proxy/testdata/deployments/custom.yaml
  internal/infrastructure/kubernetes/ratelimit/resource_provider.go
  internal/infrastructure/kubernetes/ratelimit/resource_provider_test.go
  internal/infrastructure/kubernetes/ratelimit/testdata/deployments/custom.yaml
  site/content/en/latest/api/extension_types.md
Labels: road-to-ga

#2799 feat(egctl): add support for egctl to translate from gateway-api resources to IR
  internal/cmd/egctl/testdata/translate/out/quickstart.all.yaml
  internal/cmd/egctl/translate.go
  internal/cmd/egctl/translate_test.go
  site/content/en/latest/user/operations/egctl.md
Labels: road-to-ga

#2802 fix: skip the ReasonTargetNotFound for all policies
  internal/gatewayapi/backendtrafficpolicy.go
  internal/gatewayapi/clienttrafficpolicy.go
  internal/gatewayapi/envoypatchpolicy.go
  internal/gatewayapi/securitypolicy.go
  internal/gatewayapi/testdata/backendtrafficpolicy-no-status-for-unknown-gateway-or-route.in.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-no-status-for-unknown-gateway-or-route.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-no-status-for-unknown-gateway.in.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-no-status-for-unknown-gateway.out.yaml
  internal/gatewayapi/testdata/envoypatchpolicy-no-status-for-unknown-gateway.in.yaml
  internal/gatewayapi/testdata/envoypatchpolicy-no-status-for-unknown-gateway.out.yaml
  internal/gatewayapi/testdata/securitypolicy-no-status-for-unknown-gateway-or-route.in.yaml
  internal/gatewayapi/testdata/securitypolicy-no-status-for-unknown-gateway-or-route.out.yaml
  internal/gatewayapi/translator_test.go
Labels: road-to-ga

#2833 bug: compute endpointType for all protocol types
  internal/xds/translator/cluster.go
  internal/xds/translator/testdata/in/xds-ir/tls-route-passthrough.yaml
  internal/xds/translator/testdata/out/xds-ir/tls-route-passthrough.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/tls-route-passthrough.endpoints.yaml
  internal/xds/translator/testdata/out/xds-ir/tls-route-passthrough.listeners.yaml
  internal/xds/translator/translator.go
Labels: road-to-ga

#2835 Fix: failed to create envoy-oidc-hmac secret when upgrading EG
  internal/cmd/certgen.go
  internal/provider/kubernetes/secrets.go
  internal/provider/kubernetes/secrets_test.go
Labels: road-to-ga

#2840 [Release-1.0] pin envoy to v1.29.2
  api/v1alpha1/shared_types.go
  internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/disable-prometheus.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/override-labels-and-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/patch-deployment.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/shutdown-manager.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-concurrency.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-extra-args.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-image-pull-secrets.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-node-selector.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-topology-spread-constraints.yaml
Labels: road-to-ga

#2818 feat: Support Upstream TLS to multiple Backends
  internal/xds/translator/cluster.go
  internal/xds/translator/testdata/in/xds-ir/http-route-with-tlsbundle-multiple-certs.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-tls-system-truststore.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-tls-system-truststore.endpoints.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-tlsbundle-multiple-certs.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-tlsbundle-multiple-certs.endpoints.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-tlsbundle-multiple-certs.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-tlsbundle-multiple-certs.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-tlsbundle-multiple-certs.secrets.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-tlsbundle.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-with-tlsbundle.endpoints.yaml
  internal/xds/translator/translator.go
  internal/xds/translator/translator_test.go
Labels: road-to-ga

#2851 docs: mtls to the gateway
  site/content/en/latest/user/security/mutual-tls.md
Labels: road-to-ga

#2856 ignore finalizers when comparing envoy proxy svc
  internal/infrastructure/kubernetes/resource/resource.go
  internal/infrastructure/kubernetes/resource/resource_test.go
Labels: road-to-ga

#2864 fix: Address race condition disrupting graceful shutdown process
  internal/cmd/envoy/shutdown_manager.go
Labels: road-to-ga

#2857 docs: move Design docs under "Get Involved"
  site/content/en/latest/contributions/design/_index.md
  site/content/en/latest/contributions/design/accesslog.md
  site/content/en/latest/contributions/design/backend-traffic-policy.md
  site/content/en/latest/contributions/design/bootstrap.md
  site/content/en/latest/contributions/design/client-traffic-policy.md
  site/content/en/latest/contributions/design/config-api.md
  site/content/en/latest/contributions/design/eg-metrics.md
  site/content/en/latest/contributions/design/egctl.md
  site/content/en/latest/contributions/design/envoy-patch-policy.md
  site/content/en/latest/contributions/design/extending-envoy-gateway.md
  site/content/en/latest/contributions/design/gatewayapi-translator.md
  site/content/en/latest/contributions/design/goals.md
  site/content/en/latest/contributions/design/local-envoy-gateway.md
  site/content/en/latest/contributions/design/metrics.md
  site/content/en/latest/contributions/design/pprof.md
  site/content/en/latest/contributions/design/rate-limit.md
  site/content/en/latest/contributions/design/security-policy.md
  site/content/en/latest/contributions/design/system-design.md
  site/content/en/latest/contributions/design/tcp-udp-design.md
  site/content/en/latest/contributions/design/tracing.md
  site/content/en/latest/contributions/design/watching.md
  site/content/en/latest/user/security/basic-auth.md
  site/content/en/latest/user/security/cors.md
  site/content/en/latest/user/security/jwt-authentication.md
  site/content/en/latest/user/security/oidc.md
  site/content/en/latest/user/traffic/gatewayapi-support.md
Labels: documentation, road-to-ga

#2778 Update the user doc for OIDC
  site/content/en/latest/user/security/oidc.md
Labels: road-to-ga

#2876 fix: Don't override the ALPN array if HTTP/3 is enabled.
  api/v1alpha1/clienttrafficpolicy_types.go
  charts/gateway-helm/crds/generated/gateway.envoyproxy.io_clienttrafficpolicies.yaml
  internal/gatewayapi/clienttrafficpolicy.go
  internal/gatewayapi/testdata/clienttrafficpolicy-http3.out.yaml
  internal/xds/translator/testdata/in/xds-ir/http3.yaml
  internal/xds/translator/testdata/out/xds-ir/http3.listeners.yaml
  test/cel-validation/clienttrafficpolicy_test.go
Labels: road-to-ga

#2862 [e2e] eg release upgrade test
  go.mod
  go.sum
  test/e2e/testdata/eg-upgrade.yaml
  test/e2e/tests/eg_upgrade.go
  test/e2e/upgrade/eg_upgrade_test.go
  tools/make/kube.mk
Labels: road-to-ga

#2868 Docs for ext auth
  examples/kubernetes/ext-auth-grpc-service.yaml
  examples/kubernetes/ext-auth-http-service.yaml
  site/content/en/latest/user/security/ext-auth.md
Labels: road-to-ga

#2884 docs: backend tls policy
  site/content/en/latest/user/security/backend-tls.md
Labels: road-to-ga

#2846 feat: add PolicyStatus for BackendTrafficPolicy
  api/v1alpha1/backendtrafficpolicy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
  go.mod
  internal/gatewayapi/backendtrafficpolicy.go
  internal/gatewayapi/helpers.go
  internal/gatewayapi/testdata/backendtrafficpolicy-no-status-for-unknown-gateway-or-route.in.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-no-status-for-unknown-gateway-or-route.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-status-conditions.in.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-status-conditions.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-status-fault-injection.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-circuitbreakers-error.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-circuitbreakers.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-healthcheck.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-loadbalancer.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-local-ratelimit-default-route-level-limit.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-local-ratelimit-invalid-limit-unit.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-local-ratelimit-invalid-match-type.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-local-ratelimit-invalid-multiple-route-level-limits.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-local-ratelimit.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-proxyprotocol.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-ratelimit-invalid-regex.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-ratelimit.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-retries.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-same-prefix-httproutes.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-tcpkeepalive.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-timeout-error.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-timeout.out.yaml
  internal/gatewayapi/testdata/httproute-and-backendtrafficpolicy-with-timeout-error.out.yaml
  internal/gatewayapi/testdata/httproute-and-backendtrafficpolicy-with-timeout.out.yaml
  internal/gatewayapi/testdata/merge-with-isolated-policies.out.yaml
  internal/message/types.go
  internal/provider/kubernetes/controller.go
  internal/provider/kubernetes/status.go
  internal/status/backendtrafficpolicy.go
  internal/status/policy.go
  site/content/en/latest/api/extension_types.md
  test/e2e/tests/local_ratelimit.go
  test/e2e/tests/utils.go
Labels: road-to-ga

#2885 Change the Merge behavior to Replace for SecurityPolicy
  internal/gatewayapi/securitypolicy.go
  internal/gatewayapi/testdata/securitypolicy-override-replace.in.yaml
  internal/gatewayapi/testdata/securitypolicy-override-replace.out.yaml
Labels: road-to-ga

#2845 chore: remove ProcessBackendTLSPoliciesAncestorRef
  internal/gatewayapi/backendtlspolicy.go
  internal/gatewayapi/translator.go
  internal/provider/kubernetes/controller.go
Labels: road-to-ga

#2888 Change the Merge behavior to Replace for BackendTrafficPolicy
  internal/gatewayapi/backendtrafficpolicy.go
  internal/gatewayapi/testdata/backendtrafficpolicy-override-replace.in.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-override-replace.out.yaml
Labels: road-to-ga

#2898 shutdown drainTimeout should also affect envoy drain time
  internal/infrastructure/kubernetes/proxy/resource.go
  internal/infrastructure/kubernetes/proxy/testdata/deployments/shutdown-manager.yaml
Labels: road-to-ga

#2902 skip publishing empty status for policies
  internal/gatewayapi/runner/runner.go
  internal/provider/kubernetes/controller.go
  internal/xds/translator/runner/runner.go
Labels: road-to-ga

#2895 feat: add PolicyStatus for ClientTrafficPolicy
  api/v1alpha1/clienttrafficpolicy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/gateway-helm/crds/generated/gateway.envoyproxy.io_clienttrafficpolicies.yaml
  internal/gatewayapi/backendtrafficpolicy.go
  internal/gatewayapi/clienttrafficpolicy.go
  internal/gatewayapi/helpers.go
  internal/gatewayapi/testdata/clienttrafficpolicy-client-ip-detection.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-headers.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-http10.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-http3.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-mtls.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-no-status-for-unknown-gateway.in.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-no-status-for-unknown-gateway.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-path-settings.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-preserve-case.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-proxyprotocol.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-status-conditions.in.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-status-conditions.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-tcp-keepalive.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-timeout-with-error.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-timeout.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-tls-settings.out.yaml
  internal/gatewayapi/testdata/clienttrafficpolicy-trailers.out.yaml
  internal/gatewayapi/testdata/conflicting-policies.out.yaml
  internal/gatewayapi/testdata/merge-with-isolated-policies.out.yaml
  internal/message/types.go
  internal/provider/kubernetes/controller.go
  internal/provider/kubernetes/status.go
  internal/status/clienttrafficpolicy.go
  site/content/en/latest/api/extension_types.md
Labels: road-to-ga

#3002 fix: do nof forward not matching prefilights to backends
  go.mod
  go.sum
  internal/xds/extensions/extensions.gen.go
  internal/xds/translator/cors.go
  internal/xds/translator/testdata/out/xds-ir/cors.routes.yaml
Labels: release-note

#2982 Fix: nil secret in resourceversiontable
  internal/xds/translator/testdata/out/xds-ir/http-route-with-tls-system-truststore.secrets.yaml
  internal/xds/translator/translator.go
  internal/xds/translator/translator_test.go
  internal/xds/types/resourceversiontable.go
Labels: cherrypick/release-v1.0

#2532 feat: add Chinese language support for doc site
  site/content/zh/_index.md
  site/content/zh/about/featured-background.jpg
  site/content/zh/about/index.md
  site/content/zh/announcements/_index.md
  site/content/zh/blog/_index.md
  site/content/zh/featured-background.jpg
  site/content/zh/latest/_index.md
  site/content/zh/latest/contributions/_index.md
  site/content/zh/search.md
  site/hugo.toml
Labels: documentation

#2970 fix: add missing http filters to the http filter chain
  internal/gatewayapi/securitypolicy.go
  internal/xds/translator/httpfilters.go
  internal/xds/translator/testdata/in/xds-ir/multiple-listeners-same-port-with-different-filters.yaml
  internal/xds/translator/testdata/out/xds-ir/multiple-listeners-same-port-with-different-filters.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/multiple-listeners-same-port-with-different-filters.endpoints.yaml
  internal/xds/translator/testdata/out/xds-ir/multiple-listeners-same-port-with-different-filters.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/multiple-listeners-same-port-with-different-filters.routes.yaml
  internal/xds/translator/translator.go
  internal/xds/translator/translator_test.go
Labels: cherrypick/release-v1.0

#3022 fix: allow websockets in url rewrite
  internal/xds/translator/route.go
  internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-root-path-url-prefix.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-fullpath.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-host.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-prefix.routes.yaml
Labels: cherrypick/release-v1.0
