Repository envoyproxy/gateway, pull requests merged in 2025-05, with the labels that each got.

#5740 fix: httproute precedence by considering header/query match type
  internal/gatewayapi/sort.go
  internal/gatewayapi/testdata/httproute-with-header-match-diff-number.in.yaml
  internal/gatewayapi/testdata/httproute-with-header-match-diff-number.out.yaml
  internal/gatewayapi/testdata/httproute-with-header-match-diff-type.in.yaml
  internal/gatewayapi/testdata/httproute-with-header-match-diff-type.out.yaml
  internal/gatewayapi/testdata/httproute-with-query-match-diff-number.in.yaml
  internal/gatewayapi/testdata/httproute-with-query-match-diff-number.out.yaml
  internal/gatewayapi/testdata/httproute-with-query-match-diff-type.in.yaml
  internal/gatewayapi/testdata/httproute-with-query-match-diff-type.out.yaml
Labels: cherrypick/release-v1.2.9, cherrypick/release-v1.3.3

#5945 fix: Fixed typo in error message.
  internal/provider/kubernetes/kubernetes.go
Labels: cherrypick/release-v1.3.3

#5953 fix: process remaining gatewayClasses after encountering an err
  internal/provider/kubernetes/controller.go
Labels: cherrypick/release-v1.3.3

#5671 fix: do not add tls inspector filter to quic listener
  internal/xds/translator/listener.go
  internal/xds/translator/server_names_match_test.go
Labels: cherrypick/release-v1.3.3

#6029 e2e: fix backend tls test
  test/e2e/e2e_test.go
  test/e2e/testdata/backend-tls-settings-client-cert-rotation.yaml
  test/e2e/testdata/backend-tls-settings.yaml
  test/e2e/testdata/expect/echo-service-tls-settings-new-mtls-secret.yaml
  test/e2e/testdata/expect/echo-service-tls-settings-res.yaml
  test/e2e/testdata/expect/echo-service-tls-settings-updated-tls-settings.yaml
  test/e2e/tests/backend_tls_settings.go
Labels: cherrypick/release-v1.4.1

#6103 fix: add FullDuplexStreamed to enum
  api/v1alpha1/ext_proc_types.go
  charts/gateway-crds-helm/templates/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml
  charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml
  test/helm/gateway-crds-helm/all.out.yaml
  test/helm/gateway-crds-helm/envoy-gateway-crds.out.yaml
Labels: cherrypick/release-v1.4.1

#5455 api(oidc): adds support in OIDC api to optionally deny redirects
  api/v1alpha1/oidc_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/gateway-crds-helm/templates/generated/gateway.envoyproxy.io_securitypolicies.yaml
  charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
  site/content/en/latest/api/extension_types.md
  test/helm/gateway-crds-helm/all.out.yaml
  test/helm/gateway-crds-helm/envoy-gateway-crds.out.yaml
Labels: kind/enhancement

#5988 use sds to fetch the client certificate for envoy-ratelimit TLS connections
  internal/gatewayapi/globalresources.go
  internal/gatewayapi/testdata/backendtrafficpolicy-strategic-merge-global-ratelimit.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-ratelimit.out.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-with-shared-ratelimit.out.yaml
  internal/gatewayapi/testdata/base/base.yaml
  internal/gatewayapi/translator.go
  internal/gatewayapi/translator_test.go
  internal/ir/xds.go
  internal/ir/xds_test.go
  internal/ir/zz_generated.deepcopy.go
  internal/provider/kubernetes/controller.go
  internal/provider/kubernetes/predicates.go
  internal/xds/translator/globalresources.go
  internal/xds/translator/ratelimit.go
  internal/xds/translator/testdata/in/xds-ir/jwt-ratelimit.yaml
  internal/xds/translator/testdata/in/xds-ir/ratelimit-custom-domain.yaml
  internal/xds/translator/testdata/in/xds-ir/ratelimit-disable-headers.yaml
  internal/xds/translator/testdata/in/xds-ir/ratelimit-endpoint-stats.yaml
  internal/xds/translator/testdata/in/xds-ir/ratelimit-global-shared.yaml
  internal/xds/translator/testdata/in/xds-ir/ratelimit-headers-and-cidr.yaml
  internal/xds/translator/testdata/in/xds-ir/ratelimit-multi-global-shared.yaml
  internal/xds/translator/testdata/in/xds-ir/ratelimit-sourceip.yaml
  internal/xds/translator/testdata/in/xds-ir/ratelimit.yaml
  internal/xds/translator/testdata/out/xds-ir/jwt-ratelimit.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/jwt-ratelimit.secrets.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-custom-domain.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-custom-domain.secrets.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-disable-headers.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-disable-headers.secrets.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-endpoint-stats.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-endpoint-stats.secrets.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-global-shared.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-global-shared.secrets.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-headers-and-cidr.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-headers-and-cidr.secrets.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-multi-global-shared.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-multi-global-shared.secrets.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-sourceip.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-sourceip.secrets.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit.clusters.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit.secrets.yaml
  internal/xds/translator/translator.go
  test/e2e/e2e_test.go
Labels: cherrypick/release-v1.4.1

#6169 fix: return early from buildwasms
  internal/cmd/egctl/testdata/translate/out/backend-endpoint.all.yaml
  internal/gatewayapi/envoyextensionpolicy.go
  release-notes/current.yaml
Labels: cherrypick/release-v1.4.1

#6174 chore: bump go and purego
  examples/envoy-ext-auth/Dockerfile
  examples/envoy-ext-auth/go.mod
  examples/extension-server/go.mod
  examples/grpc-ext-proc/Dockerfile
  examples/grpc-ext-proc/go.mod
  examples/preserve-case-backend/Dockerfile
  examples/preserve-case-backend/go.mod
  examples/simple-extension-server/Dockerfile
  examples/simple-extension-server/go.mod
  examples/static-file-server/Dockerfile
  examples/static-file-server/go.mod
  go.mod
  go.sum
  site/go.mod
Labels: cherrypick/release-v1.4.1

#6041 validate gateway namespace mode and merged gateways
  internal/gatewayapi/translator_test.go
  internal/provider/kubernetes/controller.go
  internal/provider/kubernetes/controller_test.go
  test/e2e/merge_gateways/merge_gateways_test.go
Labels: cherrypick/release-v1.4.1

#6133 fix: Use quoted values zone annotation in topology injector
  internal/cmd/egctl/testdata/translate/out/default-resources.all.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/custom.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/default-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/default.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/disable-prometheus.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/extension-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/gateway-namespace-mode.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/override-labels-and-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/patch-daemonset.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/shutdown-manager.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/volumes.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-extra-args.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-image-pull-secrets.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-name.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-node-selector.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-topology-spread-constraints.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/custom.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/custom_with_initcontainers.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/default-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/disable-prometheus.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/dual-stack.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/extension-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/gateway-namespace-mode.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/ipv6.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/override-labels-and-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/patch-deployment.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/shutdown-manager.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/volumes.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-empty-memory-limits.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-extra-args.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-image-pull-secrets.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-name.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-node-selector.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-topology-spread-constraints.yaml
  internal/infrastructure/kubernetes/proxy/testdata/gateway-namespace-mode/deployment.yaml
  internal/provider/kubernetes/topology_injector.go
  internal/provider/kubernetes/topology_injector_test.go
  internal/xds/bootstrap/bootstrap.yaml.tpl
  internal/xds/bootstrap/testdata/render/custom-server-port.yaml
  internal/xds/bootstrap/testdata/render/custom-stats-matcher.yaml
  internal/xds/bootstrap/testdata/render/disable-prometheus.yaml
  internal/xds/bootstrap/testdata/render/enable-prometheus-brotli-compression.yaml
  internal/xds/bootstrap/testdata/render/enable-prometheus-gzip-compression.yaml
  internal/xds/bootstrap/testdata/render/enable-prometheus.yaml
  internal/xds/bootstrap/testdata/render/ipv6.yaml
  internal/xds/bootstrap/testdata/render/otel-metrics-backendref.yaml
  internal/xds/bootstrap/testdata/render/otel-metrics.yaml
  internal/xds/bootstrap/testdata/render/with-max-heap-size-bytes.yaml
  release-notes/current.yaml
  tools/hack/create-cluster.sh
Labels: cherrypick/release-v1.4.1

#6072 Fix shared=true when no clientSelector,
  internal/xds/translator/ratelimit.go
  internal/xds/translator/testdata/out/xds-ir/ratelimit-global-shared.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/ratelimit-multi-global-shared.listeners.yaml
  test/e2e/e2e_test.go
  test/e2e/testdata/ratelimit-global-shared-and-unshared-header-match.yaml
  test/e2e/tests/ratelimit.go
Labels: cherrypick/release-v1.4.1

#6221 remove infra ENVOY_GATEWAY_NAMESPACE and introduce ENVOY_POD_NAMESPACE envVar for accesslog
  internal/infrastructure/kubernetes/proxy/resource.go
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/component-level.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/custom.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/default-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/default.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/disable-prometheus.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/extension-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/gateway-namespace-mode.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/override-labels-and-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/patch-daemonset.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/shutdown-manager.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/volumes.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-concurrency.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-extra-args.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-image-pull-secrets.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-name.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-node-selector.yaml
  internal/infrastructure/kubernetes/proxy/testdata/daemonsets/with-topology-spread-constraints.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/bootstrap.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/component-level.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/custom.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/custom_with_initcontainers.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/default-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/default.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/disable-prometheus.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/dual-stack.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/extension-env.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/gateway-namespace-mode.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/ipv6.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/override-labels-and-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/patch-deployment.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/shutdown-manager.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/volumes.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-annotations.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-concurrency.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-empty-memory-limits.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-extra-args.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-image-pull-secrets.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-name.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-node-selector.yaml
  internal/infrastructure/kubernetes/proxy/testdata/deployments/with-topology-spread-constraints.yaml
  internal/infrastructure/kubernetes/proxy/testdata/gateway-namespace-mode/deployment.yaml
  internal/xds/translator/accesslog.go
  internal/xds/translator/testdata/out/xds-ir/accesslog-cel.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/accesslog-endpoint-stats.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/accesslog-formatters.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/accesslog-multi-cel.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/accesslog-types.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/accesslog-with-format.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/accesslog.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/dns-lookup-family.listeners.yaml
  site/content/en/latest/tasks/observability/proxy-trace.md
  site/content/en/latest/tasks/operations/customize-envoyproxy.md
  test/e2e/testdata/btp-tracing.yaml
  test/e2e/testdata/tracing-datadog.yaml
  test/e2e/testdata/tracing-otel.yaml
  test/e2e/testdata/tracing-zipkin.yaml
  test/e2e/tests/accesslog.go
  test/fuzz/testdata/FuzzGatewayAPIToXDS/proxy_tracing
Labels: cherrypick/release-v1.4.1

#6217 Keep ALPN configuration for listeners with overlapping certificates when ALPN is explicitly set via ClientTrafficPolicy
  internal/gatewayapi/listener.go
  internal/gatewayapi/listener_test.go
  internal/gatewayapi/testdata/gateway-with-multiple-https-listeners-with-overlapping-certs.out.yaml
  internal/gatewayapi/testdata/gateway-with-multiple-https-listeners-with-overlapping-hostnames-and-certs-merged-gateways.out.yaml
  internal/gatewayapi/testdata/gateway-with-multiple-https-listeners-with-overlapping-hostnames-and-certs.out.yaml
  internal/gatewayapi/testdata/gateway-with-multiple-https-listeners-with-overlapping-hostnames-merged-gateways.out.yaml
  internal/gatewayapi/testdata/gateway-with-multiple-https-listeners-with-overlapping-hostnames.out.yaml
  internal/xds/translator/listener.go
  internal/xds/translator/testdata/in/xds-ir/listener-overlapping-tls-config.yaml
  internal/xds/translator/testdata/out/xds-ir/listener-overlapping-tls-config.listeners.yaml
  internal/xds/translator/testdata/out/xds-ir/listener-overlapping-tls-config.routes.yaml
  internal/xds/translator/testdata/out/xds-ir/listener-overlapping-tls-config.secrets.yaml
  release-notes/current.yaml
Labels: cherrypick/release-v1.4.1
