Repository envoyproxy/gateway, pull requests merged in 2025-09, with the labels that each got.

#6921 fix: nil pointer dereference in btp configmap indexer
  internal/provider/kubernetes/controller.go
  internal/provider/kubernetes/indexers.go
  internal/provider/kubernetes/predicates_test.go
  release-notes/current.yaml
Labels: cherrypick/release-v1.5.1

#6917 improve targetRef selection for targetSelectors
  internal/gatewayapi/backendtrafficpolicy.go
  internal/gatewayapi/clienttrafficpolicy.go
  internal/gatewayapi/envoyextensionpolicy.go
  internal/gatewayapi/extensionserverpolicy.go
  internal/gatewayapi/helpers.go
  internal/gatewayapi/helpers_test.go
  internal/gatewayapi/securitypolicy.go
  internal/gatewayapi/testdata/backendtrafficpolicy-multiple-targets-targetselector.in.yaml
  internal/gatewayapi/testdata/backendtrafficpolicy-multiple-targets-targetselector.out.yaml
Labels: cherrypick/release-v1.5.1, cherrypick/release-v1.4.4

#6953 fix: update distroless image to resolve glibc CVEs
  tools/docker/envoy-gateway/Dockerfile
Labels: cherrypick/release-v1.5.1, cherrypick/release-v1.4.4

#6959 chore: bump golang to 1.24.7
  examples/envoy-ext-auth/Dockerfile
  examples/envoy-ext-auth/go.mod
  examples/extension-server/go.mod
  examples/grpc-ext-proc/Dockerfile
  examples/grpc-ext-proc/go.mod
  examples/preserve-case-backend/Dockerfile
  examples/preserve-case-backend/go.mod
  examples/simple-extension-server/Dockerfile
  examples/simple-extension-server/go.mod
  examples/static-file-server/Dockerfile
  examples/static-file-server/go.mod
  go.mod
  site/go.mod
  tools/go.mod
Labels: cherrypick/release-v1.5.1

#7024 fix: escape regex metacharacters from path prefix string
  internal/xds/translator/route.go
  internal/xds/translator/testdata/in/xds-ir/http-route-rewrite-url-regex.yaml
  internal/xds/translator/testdata/out/xds-ir/http-route-rewrite-url-regex.routes.yaml
  release-notes/current.yaml
Labels: cherrypick/release-v1.5.2, cherrypick/release-v1.4.5
